### ISSUE TITLE
Look into making the vim plugin async

### ISSUE THREAD

**Issue by marijnh** [ternjs/tern#10]
It currently freezes the interface as it waits for Tern (with a 1 sec timeout). That's not optimal, but it seems to require some serious magic to do things asynchronously in vim.

Help welcome!

**Comment by mtangoo** [comment]
I face same problem with editor am writing. Unfortunately after first hang, th server does not work reliably anymore. did you solve this?

**Comment by angelozerr** [comment]
I had had never this problem with tern.java (with Eclipse). We have fixed too the problem of hang with tern with async mode https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#async-tern-completion

**Comment by mtangoo** [comment]
I guess I will have to go with multi threads

**Comment by CExJBoudreau** [comment]
One possibility would be to use the neovim api. 

Example: https://github.com/benekastah/neomake

It also manages to still work fine on old vim; but its synchronous in that situation.

**Comment by puremourning** [comment]
[YouCompleteMe](https://github.com/Valloric/YouCompleteMe) has support for Tern and is fully asynchronous.

**Comment by CExJBoudreau** [comment]
@puremourning Doesn't seem to be working for me. At any rate this feature would be a worthwhile improvement for the vim tern plugin. Tern freezes VIM for extended periods of time when I work on certain projects, so I no longer use it.

**Comment by puremourning** [comment]
In what way is it not working? I'm keen to help debug any issues.

**Comment by kiwanami** [comment]
Now, vim has async interface! : connect(), disconnect(), sendexpr() and sendraw()
https://groups.google.com/forum/#!topic/vim_dev/t6RbXywJZRo
