### ISSUE TITLE
extra single quote problem

### ISSUE THREAD

**Issue by hackingcat** [ternjs/tern#1002]
https://github.com/ncm2/ncm2-tern/issues/5
https://github.com/carlitux/deoplete-ternjs/issues/32
https://github.com/Shougo/deoplete.nvim/issues/599

**Comment by marijnh** [comment]
These are all in 3rd-party editor plugins, and don't occur with the standard Vim, Emacs, and ST plugins, so it seems the error is in those plugins.

**Comment by hackingcat** [comment]
https://github.com/ncm2/ncm2-tern/issues/5#issuecomment-445698299
The problem also occured in [tern_for_vim](https://github.com/ternjs/tern_for_vim).

**Comment by othree** [comment]
When reporting an issue. Please provide a major link or describe issue here instead of lots of link for we to easier understand the issue. Thanks.

Confirmed the issue. Still think where to fix. Here or editore plugins.

**Comment by othree** [comment]
This should belongs to tern_for_vim.
The response has an end position value.

**Comment by othree** [comment]
ref: https://github.com/ternjs/tern/blob/master/plugin/modules.js#L310-L311

**Comment by othree** [comment]
https://github.com/ternjs/tern_for_vim/commit/93cf8e7534e9d4f79a5ddbd3174e95621d0d27c9

**Comment by othree** [comment]
https://github.com/ternjs/tern_for_sublime/commit/ce046965d3209cb20e42c96b0d3e5e0256188a7b
