### ISSUE TITLE
Dead Link to 0.24 release in Tern website

### ISSUE THREAD

**Issue by avocadoras** [ternjs/tern#1025]
The website (http://ternjs.net/) says that there was a release on May 30 this year -- yet, the link to the release cannot be found (404 error). Such link is https://github.com/ternjs/tern/tree/0.24.0. 

What happened to this release? I just wanted to know specifically what what updated in def files for Date, DOM Node.

**Comment by othree** [comment]
Thank you, fixed by add tag to that commit.
