### ISSUE TITLE
Website still features "looking for maintainers" spiel

### ISSUE THREAD

**Issue by iamrenejr** [ternjs/tern#1029]
The [website](https://ternjs.net/) still shows this:

<img width="866" alt="Screen Shot 2019-10-02 at 11 25 46 AM" src="https://user-images.githubusercontent.com/13853458/66015995-6bf10480-e507-11e9-9ff5-12fde7d866a1.png">

The big bold note made me almost not use TernJS outright. Thank goodness I decided to investigate GitHub, [where I found the commit removing the notice](https://github.com/ternjs/tern/commit/74f14592843f24fae1eb76b3fd6837ad0a60e50b). This might be driving new developers away.

**Comment by othree** [comment]
Thanks, will update it.
