### ISSUE TITLE
[BUG] defining the type for the argument of a function

### ISSUE THREAD

**Issue by weixiongmei** [ternjs/tern#1031]
Reproduct Web: https://ternjs.net/doc/demo/index.html#simple
```javascript
function ABC(cba: string)
{
  return cba;
}
ABC( //<- Expected the hint dialog to shows "ABC(cba: string) -> string". But in the demo, it's showing "ABC(cba, string)"
```

**Comment by marijnh** [comment]
That's TypeScript (or Flow) syntax. Tern just parses _JavaScript_.

**Comment by weixiongmei** [comment]
is it possible to assign a type to the argument of the function like the ecmascript.json? So the hint can be clearer. Any workaround other than call it once? Thanks~~

**Comment by marijnh** [comment]
You can use jsdoc comments — something like `/** @param {String} cba */` above the function.

**Comment by weixiongmei** [comment]
It works like a champ, thank you so much~~~
