### ISSUE TITLE
feature request: CDN support for project libs

### ISSUE THREAD

**Issue by catphive** [ternjs/tern#175]
Often, especially when just getting started on a project, I use libraries from a CDN rather than downloading the javascript and serving it locally. It would be desirable for this to work with tern.

There are a couple of ways this could work:
1. The .tern-project libs property could accept http and https URI's.
2. The libs property could specify an html file, which would be parsed for script tags.

**Comment by aikeru** [comment]
Perhaps a better way to handle this is to download the JS files from the CDN locally while in development.

**Comment by marijnh** [comment]
Agreed. I'm going to close this as 'someone else's problem' -- there are CDNs that allow you to propose libraries, you could work with them.
