### ISSUE TITLE
Tern+CodeMirror crashes Chrome

### ISSUE THREAD

**Issue by dangoor** [ternjs/tern#198]
I'm just filing this here in case others run into this problem. Tern should not be able to crash the browser, so this is really a bug in Chromium (and I've filed it there).

For me, this URL will reliably crash Chrome:

http://dangoor.github.io/tern/doc/demo.html?crash

That is the stock Tern demo, but with:

* two different JS files (polymer and web-animations)
* useWorker = true

I find that it also crashes even with useWorker = false, which you can see here:

http://dangoor.github.io/tern/doc/demo.html?crash&noworker

(If you remove the query string, you get the normal Tern demo, which works just fine).

@marijnh: feel free to close this or keep it open for tracking until the bug is fixed in Chromium. Right now it says it's restricted, but the bug is [260811](https://code.google.com/p/chromium/issues/detail?id=260811).

**Comment by aikeru** [comment]
@dangoor I tried this in Chromium 51.0.2704.79 in Ubuntu 16.04 (64-bit) and neither URL was able to crash Chromium.

Possibly this is resolved? The bug is still restricted.

**Comment by dangoor** [comment]
@aikeru Yes, the Chromium bug is fixed. Thanks for bringing this back up!
