### ISSUE TITLE
[emacs plugin] Windows compatibility

### ISSUE THREAD

**Issue by kimgronqvist** [ternjs/tern#256]
Using Windows 7 64-bit, I had to take the following steps to get Tern to run properly in Emacs:

1. Windows can't start the tern binary directly using start-process. I added the tern binary directory to my PATH and created this bat-file called tern.bat:

       @echo off
       cd /d %~dp0
       node tern %*

2. In my Emacs-config, I manually set tern-command like so

       (setq tern-command '("tern" "--no-port-file" "--persistent"))

I'm unsure if it's possible to create a proper fix for this, as processes and the command line just work so differently on Windows.

Anyway, this workaround should probably be mentioned in the documentation.

**Comment by mseddon** [comment]
I've noticed on tern 0.8.0 under windows, quitting emacs24 with C-x C-c kills the tern server but leaves a stale .tern-port file, causing breakage for subsequent sessions until this file is deleted.  Presumably emacs is a bit too unceremonious about terminating the tern process?

**Comment by marijnh** [comment]
Yeah, process killing appears to be quite hard to do cross-platform. But in principle, the tern plugin should not keep trying to reuse the same failing port, so maybe we can debug what goes wrong there. The logic is in the `runner` lambda defined inside of `tern-run-request`, and when I test it (by creating a bogus port file), it seems to work for me -- the first request fails, but the plugin then creates a new server and connects to that in the second attempt.

**Comment by kimgronqvist** [comment]
When I try the same procedure, I just get this error message:
(file-error "make client process failed" "connection refused" :name "127.0.0.1" :buffer #<killed buffer> :host "127.0.0.1" :service 24 :nowait nil).

I've tried to use edebug to find more about the problem, but I'm not sure how to step into the runner lambda. Just using space to step forward or setting a breakpoint doesn't seem to do the trick.

**Comment by mseddon** [comment]
It seems that runner is never called. When the file-error is triggered in the callback code at:

    (tern-req port doc runner)

and this never succeeds.  tern-req's url-http appears to be blowing up and not calling the c argument (bound to the runner closure).  The stack-trace is approximately:

    make-network-process
    open-network-stream
    byte-code
    url-open-stream("127.0.0.1" #<buffer  *url-http-temp*> "127.0.0.1" 54545)
    url-http-find-free-connection("127.0.0.1" 54545)

**Comment by marijnh** [comment]
Oh, that's cute. It is supposed to call its callback when an error occurs, but I guess it doesn't always do that. It appears to be possible to use [`condition-case`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Handling-Errors.html#Handling-Errors) to catch errors, and then simply call the callback directly. Do you want to attempt to fix this yourself? (I can't reproduce the problem, so I'd have a hard time figuring out whether my patch actually fixes it.)

**Comment by kimgronqvist** [comment]
No luck with condition-case, but unwind-protect seems to do what we want! (This is also what url-http uses internally).

This code works for me:

    (setf callback (lambda (port err)
                     (if port
                         (unwind-protect
                             (tern-req port doc runner)
                           (funcall runner '((err connection-failed)) nil))
                       (funcall f err nil))))

**Comment by marijnh** [comment]
Does this patch also work for you (it preserves the error rather than making up a `connection-failed` one)?

```diff
diff --git a/emacs/tern.el b/emacs/tern.el
index 9ee0c88..d9efad8 100644
--- a/emacs/tern.el
+++ b/emacs/tern.el
@@ -167,7 +167,9 @@ list of strings, giving the binary name and arguments.")
         callback runner)
     (setf callback (lambda (port err)
                      (if port
-                         (tern-req port doc runner)
+                         (condition-case err
+                             (tern-req port doc runner)
+                           (error (funcall runner (list err) nil)))
                        (funcall f err nil))))
     (setf runner (lambda (err data)
                    (with-current-buffer buffer
```

**Comment by kimgronqvist** [comment]
Ah, so that's how you use condition-case :)

No that does not work. I don't think the error message that is returned is properly formatted for processing in the runner.

Evaluating (list err) gets me ((file-error "make client process failed" "connection refused" :name #1="127.0.0.1" :buffer #<killed buffer> :host #1# :service 4 :nowait nil)). 

I had to change this in the runner lambda:
    (cond ((or (and err (eq (cl-cadar err) 'connection-failed) (not retrying))
               (eq (caar err) 'file-error))

**Comment by marijnh** [comment]
Could you try with attached patch?

**Comment by kimgronqvist** [comment]
I've tested it for a few hours now and everything seems to be working great.

Thank you very much!

**Comment by dertuxmalwieder** [comment]
The current version in MELPA still can't find my `tern` although Emacs itself finds it. :-/

**Comment by kimgronqvist** [comment]
What sort of error message do you get? I have no trouble starting tern, but get an error message from the process with later versions. Had to revert to an older version.

**Comment by kimgronqvist** [comment]
I run version 0.13.1 btw.

**Comment by dertuxmalwieder** [comment]
It had issues finding the `tern` binary. Force-setting `(setq tern-command '("node" "c:/.../npm/node_modules/tern/bin/tern"))` solves the issue for me. It seems that this package does not look into my `PATH`.

**Comment by marijnh** [comment]
Did you verify that your Emacs actually can see your proper path? You can look at `M-x getenv PATH` to check.

**Comment by dertuxmalwieder** [comment]
Yes, that looks valid.

**Comment by svatem1** [comment]
i can confirm this issue (not finding tern unless path is changed in tern-command) still persists; tern "executable" is visible, path (appdata/roaming/npm) is among the ones returned by M-x getenv PATH, but ternjs insists on running the executable from current dir, tern command defaults to "npm", "tern"

**Comment by corintho** [comment]
I also have this problem with Emacs 24.5.1.
I have tern installed globally (`npm install -g tern`) with node v5.0.0

Executing `(executable-find "tern")` finds the proper path (in "C:\Users\<username>\AppData\Roaming\npm\tern.cmd")
That path is listed in my path variable (`M-x getenv PATH`)
If I run from a command prompt simply `tern` the server starts successfully. It also works if I run it from a shell inside Emacs.

As a workaround at the moment, I am doing this on my initialization `  (setq tern-command '("tern"))` since the default resolver for Emacs seems to find tern just fine by itself (globally at least).

**Comment by marijnh** [comment]
What was the value of `tern-command` before you set it? (And if not immediately obvious, can you figure out why that didn't work?)

**Comment by svatem1** [comment]
i think the problem is with ` (if (eq system-type 'windows-nt) (cons "node" tern-itself) tern-itself))` part of tern.el ; on windows it's by default set to something like ("node" "tern"), which incorrectly looks in current dir

**Comment by marijnh** [comment]
`tern-itself` should be the full path to tern at that point, though, except if something went wrong in the lines above, or you're not loading tern.el from a tern checkout

**Comment by svatem1** [comment]
it's not; look in [here](https://github.com/syl20bnr/spacemacs/issues/5733)
by default it's set to  `("node" "tern" "--no-port-file")` on my machine on windows

**Comment by rogersillito** [comment]
When I execute `(symbol-value 'tern-command)` I get `("node" "tern")`

**Comment by marijnh** [comment]
The relevant expression in tern.el is 

```
(let* ((script-file (or load-file-name
                          (and (boundp 'bytecomp-filename) bytecomp-filename)
                          buffer-file-name))
         (bin-file (expand-file-name "../bin/tern" (file-name-directory (file-truename script-file))))
         (tern-itself (list (if (file-exists-p bin-file) bin-file "tern"))))
    (if (eq system-type 'windows-nt) (cons "node" tern-itself) tern-itself))
```

That apparently fails to find the script file on your system, but I am not sure why. Note that it looks at some load-time variables that won't be around if you run it in `*scratch*` or similar. Could you try adding a `(print ...)` around, for example, the value of `script-file` to see what is going on?

**Comment by svatem1** [comment]
@marijnh do you know, why there's that `eq system-type 'windows-nt`? because for @corintho it works without the leading "node"; it probably has/had some reason, maybe that reason no longer applies

**Comment by rogersillito** [comment]
@svatem1 that's a good question: if I execute `:!tern` it fires up the tern server fine from emacs, conversely if I execute `:!node tern` I get the node error `Error: Cannot find module 'C:\DEV\tern'`.
The workaround of setting tern-command to value to include the full path to tern works for me.

**Comment by marijnh** [comment]
Directly running the script would rely on hashbangs (`#!/usr/bin/env node`) working on Windows. They may have started working in some windows version, or some other mechanism is making this work on your machine, but I'm pretty sure that that's not a feature you can rely on in Windows

**Comment by rogersillito** [comment]
@marijnh - I've tried to print out `script-file` as follows:

    (let* ((script-file (or load-file-name
                            (and (boundp 'bytecomp-filename) bytecomp-filename)
                            buffer-file-name))
          (bin-file (expand-file-name "../bin/tern" (file-name-directory (file-truename script-file))))
          (tern-itself (list (if (file-exists-p bin-file) bin-file "tern"))))
      (print script-file)
      (if (eq system-type 'windows-nt) (cons "node" tern-itself) tern-itself))

I'm not seeing anything (in *Messages* ?).   Where/when should I be seeing the printed value?  (I'm a spacemacs/elisp noob BTW).

**Comment by marijnh** [comment]
I'm not terribly proficient with elisp either, but I do think `print` should put something in `*Messages*`. Did you re-evaluate the expression (C-M-x when the cursor is on it)?

**Comment by svatem1** [comment]
@marijnh there's no issue with hasbangs on windows at all; what it does when set up as ("node" "tern") is that it invokes "node tern", while setting it as ("tern") just invokes tern; "node term" fails as it would fail in command line, because by nature of nodejs, it searches for tern in current dir; the question is therefore, why is it set up as ("node" "tern") on windows and not as ("tern")..

regarding print - i've tried [message](http://ergoemacs.org/emacs/elisp_printing.html) instead, but as I'm not proficient with elisp at all, it also didn't show anything in *Messages* buffer

**Comment by marijnh** [comment]
It's supposed to be set up as `"node" "/path/to/tern"`, the fact that it ends up as `"node" "tern"` is due to a problem in locating the tern script.

**Comment by svatem1** [comment]
@marijnh you're just repeating the mantra; the question is - when there's command called "tern.cmd" that is on windows equivalent to running "node /path/to/tern", why is tern.el calling just on windows (notice the eq windows-nt) "node /path/to/tern" and not just "tern".. there probably was some reason, and now it's pretty clear you don't know this reason

**Comment by marijnh** [comment]
The claim that there is no issue with hashbangs at all on windows is nonsense -- they are a complete unixism, and `/usr/bin/env` is clearly not a sensible thing to execute on windows.

**Comment by svatem1** [comment]
@marijnh you're not getting it; if you run "tern" inside windows cmd shell, ternjs starts, because by default tern.cmd is in PATH; hence setting the tern command to just ("tern") would proceed as demonstrated by @corintho couple of posts above (he's not setting the correct path for tern, he's just omitting the "node"); so the question is, why is tern.el trying to run "node /fullpathto/tern" instead of just "tern", when the latter works..

also - there are no hashbangs involved; anywhere; they may be the culprit; for different problem in different issue though

**Comment by marijnh** [comment]
What is tern.cmd and who added it to $PATH?

**Comment by svatem1** [comment]
@marijnh these are the contents of tern.cmd created either by ternjs developers or npm:

`@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\tern\bin\tern" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\node_modules\tern\bin\tern" %*
)`

for some reason they decided to not to use unixisms on windows, which was a wise choice

**Comment by marijnh** [comment]
That's probably something NPM does. Unless I'm completely misunderstanding where it came from, that will only work when Tern is installed _globally_ through NPM, which I don't want to rely on.

**Comment by rogersillito** [comment]
@marijnh - I believe that's the recommended setup though for tern with emacs?

**Comment by marijnh** [comment]
None of the documentation I wrote recommends that. It's a sensible way to install it, but not the only supported way. So that's why I prefer a more general way of launching, which we were trying to debug before.

**Comment by rogersillito** [comment]
I'm coming at this as a spacemacs user - it looks like there are some conflicting docs:

http://spacemacs.org/layers/+lang/javascript/README.html

**Comment by rogersillito** [comment]
When I add in the (message script-file) block and re-evaluate tern-command, I get the following in /*messages/*:

*d:/tools/emacs/config/.emacs.d/elpa/tern-20151228.511/tern.el*

**Comment by svatem1** [comment]
@marijnh if i have 10 projects, do you expect me to install ternjs 10 times locally?

**Comment by rogersillito** [comment]
@svatem1 Yes personally I would much prefer a global install of tern for convenience - given it's nature/purpose.

**Comment by corintho** [comment]
> That's probably something NPM does. Unless I'm completely misunderstanding where it came from, that will only work when Tern is installed globally through NPM, which I don't want to rely on.
@marijnh That's exactly how I have it installed, I tried to stress on the point that I have it installed globally. I agree that it's not a reasonable "solution" to force users to have it globally, but since that works for me, I listed it as a workaround.



> if i have 10 projects, do you expect me to install ternjs 10 times locally?
@svatem1 that may make sense, for example, when using eslint, every single project I have, has a local copy of eslint with plugins and all versions matching. Not sure if that applies to tern, but if it's possible (and makes sense) to install it locally, it's something that must be considered.

**Comment by marijnh** [comment]
@rogersillito Thanks! That looks like the .el file ends up in a place away from the tern install/checkout, which breaks the auto-script-finding. That's a Spacemacs thing, I guess. Attached patch tries to work around this by reshuffling the conditionals to never generate `("node" "tern")`.

**Comment by svatem1** [comment]
@corintho sorry, for me saying "i have eslint installed locally for 10 projects and maintain 10 setups for 10 different versions (because that's the only reason i can imagine anybody would do that) is like saying "i have make installed 20 times and i maintain 20 different versions of makefiles according to those versions"

**Comment by svatem1** [comment]
@marijnh  i think it's not spacemacs' thing, it's thing of package manager emacs uses imho

**Comment by corintho** [comment]
@svatem1 well, I didn't intend to start discussing another library around here. Suffice it to say that if you have two projects, one in angular + es5 (and no babel), and one with react + es6 + babel transforms, its going to be quite a thing to have that working with a global installation of eslint (and all the needed plugins alongside). But with local versions, that's pretty easy to solve.
Anyway, the problem above is mostly due to plugins interfering with each other and requiring specific versions of eslint. I am not sure if that is a problem with tern itself...

**Comment by marijnh** [comment]
No one is suggesting @svatem1 installs 10 versions of Tern. Maybe let's get this issue back on the rails and discuss whether my patch helps instead?

**Comment by svatem1** [comment]
@corintho ok, thanks, was really interested in that, coming from different world

@marijnh ok, will try

**Comment by svatem1** [comment]
@marijnh seems to solve the problem for my setup (= installed globally on win); tern-command is now ("tern")

**Comment by rogersillito** [comment]
@marijnh: Same results for me as @svatem1 , with a globally-installed tern.  Thanks!
