### ISSUE TITLE
Add support for @typedef

### ISSUE THREAD

**Issue by andreypopp** [ternjs/tern#293]
It would good to be able to define own type aliases with `@typedef` and `@property` http://usejsdoc.org/tags-typedef.html

**Comment by yarray** [comment]
Sorry for commenting this old thread. But does @typedef with @property also supported? It seems the inferred type of t in function test is {}.

``` js
/**
 * @typedef {Object} Person
 * @property {string} name how the person is called
 * @property {number} age how many years the person lived
 */

/**
 * test
 *
 * @param {Person} t
 */
function test(t) {
}
```

**Comment by marijnh** [comment]
Attached patch adds some support for `@property` declarations (when they immediately follow a `@typedef`)

**Comment by yarray** [comment]
It works like a charm. Thanks a lot!
