### ISSUE TITLE
False positives after changing the type of a local var in the code

### ISSUE THREAD

**Issue by dgutov** [ternjs/tern#349]
Rough outline:

1. Assign a string to a var.

2. Complete the var's property.

3. Backspace the last two lines up to the assignment, assign a different kind of value.

4. Complete the var's property, see the `String` properties included in the list.

Maybe save the buffer a few times during the process, doesn't matter.

Here's a video:

https://drive.google.com/file/d/0B8g15weL-SZLdF9udEVrQzdsRGs/edit?usp=sharing

Initially reported as https://github.com/proofit404/company-tern/issues/12.

**Comment by aikeru** [comment]
@dgutov 
This doesn't seem to be an issue anymore?
I tried starting with:
```
var x =  "foo";
x. //started completion here, got completions for string
```
then backspaced/deleted the assignment to x ("foo") and replace with number (9)
```
var x = 9;
x. //got completions for number
```
Also, the video link does not seem to work, I get "Sorry, the file you have requested does not exist."

I tested this against tern 0.19 on Ubuntu in a .js file, using Vim + YCM as my client to tern.

**Comment by dgutov** [comment]
> This doesn't seem to be an issue anymore?

Looks like it, thanks.
