### ISSUE TITLE
requirejs: Setting module.exports in simplified CommonJS wrapper not working

### ISSUE THREAD

**Issue by herrernst** [ternjs/tern#462]
With RequireJS, one could use a simplified CommonJS Wrapper and set the value of the exported module by returning it in the callback/wrapper function. This is [supported in Tern already](http://requirejs.org/docs/commonjs.html#exports). But in RequireJS, one could also set the exported object by assigning it to `module.exports`:

> There are some CommonJS systems, mainly Node, that allow setting the exported value by assigning the exported value as module.exports. That idiom is supported by RequireJS
> - http://requirejs.org/docs/commonjs.html#exports

Maybe you would also like to support that (should be simple). Example:

``` javascript
define(function(require, exports, module) {

  function Person(name) {
    this.name = name;
  }

  //if using just this, Tern doesn't get it, but works with RequireJS
  module.exports = Person;

  //this works with Tern already
  return Person;

});
```

**Comment by marijnh** [comment]
I followed up with patch 9ecb8285580a049b, which fixed the test suite and might also fix your case.

**Comment by herrernst** [comment]
I've also tried with 9ecb828, but it doesn't help. Your work is very appreciated!

**Comment by marijnh** [comment]
Right, there was another problem. Attached patch seems to help.

**Comment by herrernst** [comment]
It works now, thank you very much!
