### ISSUE TITLE
typescript file moved

### ISSUE THREAD

**Issue by tmcw** [ternjs/tern#468]
[from_ts](https://github.com/marijnh/tern/blob/master/bin/from_ts) expects a typescript file at `/bin/typescript.js` in the typescript package, but [this file no longer exists](https://github.com/Microsoft/TypeScript/tree/master/bin) - looks like it may have moved to `tsc.js`.

**Comment by angelozerr** [comment]
@tmcw have you resolved this issue? I have the same problem.

**Comment by marijnh** [comment]
It seems the Typescript compiler was overhauled again, and no longer exposes the files and interfaces I am using. That's it for me, I'm no longer interested in tracking their unstable interfaces. Does anyone want to take over maintenance of `from_ts` and move it to a separate repository?

**Comment by angelozerr** [comment]
>  Does anyone want to take over maintenance of from_ts and move it to a separate repository?

@tmcw it should be fantastic if you could do that. I'm very interested with this feature to do teh same feature than WebStorm https://github.com/angelozerr/tern.java/issues/227

**Comment by tmcw** [comment]
Sorry, I think I have the same feelings on TypeScript's API as @marijnh - it's really thinly documented and doesn't seem like a focus of the project.
