### ISSUE TITLE
JSDoc @param type Object[] issue

### ISSUE THREAD

**Issue by jwhitmarsh** [ternjs/tern#655]
Autocomplete is suggesting malformed type `[{sortKey: string]}` where @param is defined as `Object[]`. 

![screen shot 2015-09-30 at 14 05 10](https://cloud.githubusercontent.com/assets/8026009/10193652/53a0fdca-677c-11e5-8945-0a7e11e10d53.png)

**Comment by marijnh** [comment]
The `Object[]` annotation for arrays is not part of JSDoc, I believe, but it's easy to support (see attached patch). As for the corrupted type, I couldn't reproduce that, but then, I didn't type in all of the text that you screenshotted (hint: pasting is more useful when dealing with text)
