### ISSUE TITLE
crash after accidental syntax error for es6 modules

### ISSUE THREAD

**Issue by arisAlexis** [ternjs/tern#656]
the following crash happens after writing "import * from" which is a syntax mistake

I am using eslint and my .tern file is:

{
"libs": [
"browser",
"ecma5",
"ecma6"
],
"loadEagerly": [
"services/*/.js"
],
"plugins":{
"doc_comment": {
"fullDocs": true
}
}
}

atom version is latest 1.0.1

error
undefined Unexpected token
at line 13 col 1 in services/mailService.js
File 1Project 11 Issueservices/mailService.js11:10
LFUTF-8JavaScriptmaster2+44
atom-ternjs
/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1045 return scope.defProp(nameNode.name, nameNode); ^ TypeError: Cannot read property 'name' of undefined at addVar (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1045:34) at Object.walk.make.ImportDeclaration (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1149:9) at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.skipThrough (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:168:3) at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.base.Program.base.BlockStatement as Program at c (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:68:35) at Object.recursive (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/node_modules/acorn/dist/walk.js:69:5) at Object.exports.analyze (/home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:1709:10) at /home/aris/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:267:13

**Comment by marijnh** [comment]
Is this the same as #643? Does cc88ecc fix it?

**Comment by wKich** [comment]
```
Failed to start server:
/Users/kich/WebDev/forms/node.js:1
(function (exports, require, module, __filename, __dirname) { import Promise from 'bluebird'
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at loadPlugins (/Users/kich/.vim/bundle/tern_for_vim/node_modules/tern/bin/tern:126:15)
    at startServer (/Users/kich/.vim/bundle/tern_for_vim/node_modules/tern/bin/tern:170:17)
```

tern_for_vim@0.5.0 /Users/kich/.vim/bundle/tern_for_vim
└── tern@0.18.0

my `.tern-config`
```
{
  "ecmaVersion": 6,
  "plugins": {
    "complete_strings": {
      "maxLength": 15
    },
    "doc_comment": {
      "fullDocs": true
    },
    "node": {},
    "requirejs": {},
    "modules": {},
    "es_modules": {}
  }
}
```

**Comment by marijnh** [comment]
The `/Users/kich/WebDev/forms/node.js` file that the crash you show comes from doesn't seem to have anything to do with Tern.
