### ISSUE TITLE
tooltip bug in demo

### ISSUE THREAD

**Issue by gujiman** [ternjs/tern#668]
The tooltip does not go away when changing projects:

step1) if you goto the demo:
http://ternjs.net/doc/demo/index.html

step2) click inside any function to bring up the tooltip i.e 
var bar = foo.slice(foo.slice({click here}

step3) once the tooltip comes up then change the project to a different project (from the drop down menu)

The tooltip does not go away and remains.

**Comment by gujiman** [comment]
because i'm using jquery i added the following code to the file http://ternjs.net/doc/demo/demo.js:

function initProject(name, c) {
$(".CodeMirror-Tern-tooltip").remove();
....
....
...
}

**Comment by marijnh** [comment]
Good point. Attached patches fix this.
