### ISSUE TITLE
removing first file error

### ISSUE THREAD

**Issue by gujiman** [ternjs/tern#669]
step 1) goto http://ternjs.net/doc/demo/index.html#requirejs

step 2) select "remove this file" from drop causes an error, console error:

"Uncaught TypeError: Cannot read property 'name' of null"

Possible solution:

step 1) Open http://ternjs.net/doc/demo/demo.js

step 2) delete 'this.curDoc = null' from line 6

step 3) add 'this.curDoc = firstDoc' after line 28

**Comment by marijnh** [comment]
Thanks for debugging that! Attached patch implements your fix.
