### ISSUE TITLE
JSDoc support for parameters with properties

### ISSUE THREAD

**Issue by angelozerr** [ternjs/tern#673]
It should b ecool if ternjs could support JSDoc for parameters with properties http://usejsdoc.org/tags-param.html#parameters-with-properties

**Comment by marijnh** [comment]
It would, I guess. Want to extend the doc_comments plugin?

**Comment by angelozerr** [comment]
When I will find time, I will try to provide a PR.

**Comment by marijnh** [comment]
Implemented in #839
