### ISSUE TITLE
Class Property Initialisers Containing Functions Throw Errors

### ISSUE THREAD

**Issue by MethodGrab** [ternjs/tern#674]
atom-ternjs 0.8.4

I'm not sure if this is `atom-ternjs`related or a general `ternjs` issue so apologies if this is on the wrong repo.

When using class property Initialisers that contain functions, the following error appears:
```js
atom-ternjs
    TypeError: this.proto.gatherProperties is not a function
    at extend.gatherProperties (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:681:34)
    at Object.exports.forAllLocalsAt (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:2112:11)
    at Object.findCompletions [as run] (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:747:13)
    at run (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:254:30)
    at Object.exports.withContext (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:862:18)
    at /Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:262:13
    at analyzeAll (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:376:15)
    at doRequest (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:245:5)
    at Object.signal.mixin.request (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:159:7)
    at respond (/Users/me/Atom/packages/atom-ternjs/node_modules/tern/bin/tern:239:10)
```
This can be reproduced with the following example ([original](http://babeljs.io/blog/2015/06/07/react-on-es6-plus/)):
```js
class Video extends React.Component {
	static propTypes = {
		videoSrc: React.PropTypes.string.isRequired,
		customProp: function(props, propName, componentName) {
			if (!/matchme/.test(props[propName])) {
				return new Error('Validation failed!');
			}
		}
	}
}
```
To trigger the error, try typing anywhere inside the `customProp` function.

**Comment by marijnh** [comment]
Class properties are not in ES6, and are thus not supported by Tern. Still, the expected behavior would be for the parser to ignore them and Tern to continue working. I could not reproduce the crash by using the example code you gave in a file and running Tern on it. Could you provide me with more precise instructions for reproducing this?

**Comment by MethodGrab** [comment]
Ah ok, maybe it is `atom-ternjs` related then.
Steps to reproduce:
- Open Atom editor (v1.1.0)
- Create and save a new file containing the example code:
```js
class Video extends React.Component {
    static propTypes = {
        videoSrc: React.PropTypes.string.isRequired,
        customProp: function(props, propName, componentName) {
            if (!/matchme/.test(props[propName])) {
                return new Error('Validation failed!');
            }
        }
    }
}
```
- Reload Atom editor from `View -> Reload`
- Place your cursor inside the `'Validation failed!'` string on line 6
- The error should appear

I'm on a different machine and the error is different when placing the cursor inside the string:
```js
TypeError: Cannot read property 'Error' of undefined at extend.hasProp
```

To get the original error (`gatherProperties is not a function`) follow the steps above but instead of placing the cursor inside the string on line 6, delete line 6 and type anything into that line.

**Comment by marijnh** [comment]
This was a bug in the parser. Attached patch fixes it. I've published a new version to npm, doing `npm update` wherever Tern ended up being installed should help. (The content of these properties still won't be analyzed, but at least the crash should be gone.)

**Comment by MethodGrab** [comment]
Thanks! :+1:
