### ISSUE TITLE
Not parsing function parameter starting with $ correctly

### ISSUE THREAD

**Issue by xiongxoy** [ternjs/tern#676]
When the parameter starts with $, tern.js doesn't work as expected. 
```js
function($element) {
```

**Comment by marijnh** [comment]
Both `function foo($element) {}` and `(function($element) {})` parse fine. The fact that `function($element) {}` doesn't is a feature, since that's not valid JavaScript (the `$` doesn't have anything to do with it).

**Comment by xiongxoy** [comment]
Sorry, I will clarify the problem. 

```js
var $element = 12;
```

If I type $ in a new line, the option $element will show up, 
but if I hit enter, there will be double $$. 

I'm not sure if this is directly related to tern. Thanks @marijnh

**Comment by angelozerr** [comment]
> I'm not sure if this is directly related to tern. 

It's related to your editor. It works with CodeMirror http://ternjs.net/doc/demo/#simple and tern.java (Eclipse). I suggest you that you post your problem to the project editor which uses ternjs.

**Comment by xiongxoy** [comment]
It happens in sublime text 3. I will try to post to another project. Thanks!
