### ISSUE TITLE
lexcial-binding stripped from tern.el file-header 

### ISSUE THREAD

**Issue by steckerhalter** [ternjs/tern#685]
when using:

```cl
(package-install-file "/path/to/tern.el")
```

the installed package is missing `;;; -*- lexical-binding: t -*-` which causes it to malfunction
Emacs probably removes the line because:

```
;;; filename --- description

The description should be contained in one line. If the file needs a ‘-*-’ specification, put it after description. If this would make the first line too long, use a Local Variables section at the end of the file. 
```

see http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

could you correct that?

**Comment by marijnh** [comment]
Wow. I don't know what is stripping them out, and I am not sure I even want to know, but that is some horrible behavior. Thanks for your patch!
