### ISSUE TITLE
WebPack alias

### ISSUE THREAD

**Issue by Pieter-Jan** [ternjs/tern#686]
I tried to use version 0.16.1 with tern_for_vim and it seems that when using the "webpack" plugin, it doesn't recognise aliases, is this something that is not yet supported? Thanks

**Comment by marijnh** [comment]
I have no idea. cc @GreenGremlin @chemzqm

**Comment by chemzqm** [comment]
Yes, not supported yet.   That plugin is quite basic, it have no idea of your configuration for webpack.
A possible way I think is make the plugin configurable for custom resolve logic (or parse the file webpack.config.js ?)

**Comment by rpominov** [comment]
Maybe a better approach would be not to _parse_ webpack.config.js but simply _require()_ it like webpack itself do and read options like `resolve.root` and `resolve.alias` from the imported object.

**Comment by GreenGremlin** [comment]
In Karma, it is required in the config file, by the user.

**Comment by karlhorky** [comment]
Is this something that is considered being added? Being able to resolve files from the `resolve.root` array would also be a nice feature.

**Comment by marijnh** [comment]
A pull request that makes the webpack plugin more configurable, and maybe even makes it read `.webpack.js` files would be welcome, but I am not going to work on this myself.

**Comment by chemzqm** [comment]
I've made a PR for this #805

**Comment by aikeru** [comment]
@chemzqm @marijnh is this issue waiting on any additional work? I see that https://github.com/ternjs/tern/pull/805 and https://github.com/ternjs/tern/pull/807 seem to be already merged..

**Comment by chemzqm** [comment]
@aikeru I may need to update the documentation of plugin.
