### ISSUE TITLE
[ES6] completion for specifier doesn't work when as is sused

### ISSUE THREAD

**Issue by angelozerr** [ternjs/tern#689]
If you take the demo http://ternjs.net/doc/demo/#ES6 and you add in the index.js tab the content:

This completion works:

```javascript
import {P// here Ctrl+Space work} from "./mymath"
```
But if you add 'as', it doesn't work:

```javascript
import {P// here Ctrl+Space DOESNT work} as myMath from "./mymath"
```

**Comment by marijnh** [comment]
`import {P} as myMath from "./mymath"` is not valid ES6 syntax
