### ISSUE TITLE
How to set the !doc of function arguments

### ISSUE THREAD

**Issue by boniatillo-com** [ternjs/tern#691]
I do not see a way to set the jsdoc of the arguments of a function.

Maybe should be an alternative way to define a function using JSON syntax and not a javascript-like syntax like `fn(a: number, b: string)`. Even it can improve the speed of the server loading since it does not have to do an extra step to parse the functions signature.

**Comment by marijnh** [comment]
There is no way to _access_ the docstring for function arguments except if you are editing the code for the function itself, which you can't, for JSON-based type definitions. So I am not sure what you are hoping to accomplish here. Could you elaborate?

**Comment by boniatillo-com** [comment]
Ok let me write it again.

In the JSON type definitions you can specify the doc of functions, properties, types, etc.. but not the doc of the arguments of the functions. I think tern is using a human readable but limited syntax to express function types. I think in addition to the syntax `fn(a: number)` we can use a JSON object to specify the function information, for example, something like:

```
"MyType": {
    "staticFunction": {
		"!type": "function",
		"!args": [ {
			"!type": "number",
			"!name": "a",
			"!doc": "A non negative number"
		} ]
	},
  }
```

**Comment by marijnh** [comment]
You still did not answer my question: what would you want to do with these docs? As it is, Tern does not provide any way to access them.

**Comment by boniatillo-com** [comment]
Sorry for the confusion.

What I want with the docs is to show them in an editor, for example in an auto-complete dialog or tooltip. As it is, the doc_comment plugin is not giving the docs of the function arguments. So I created this issue to vote for that feature.

**Comment by marijnh** [comment]
Per-argument comments is not a feature that Tern currently supports, so that is why the JSON format also doesn't. I don't consider this an important enough feature to overhaul the system for it.
