### ISSUE TITLE
Query to get a decorated AST

### ISSUE THREAD

**Issue by boniatillo-com** [ternjs/tern#692]
It will be great if we have a query to get the AST of a file. Right now we can write a plugin to add new functionalities to tern but with a type-decorated AST we can develop better tools in the client side, with the client language, like Java or Python.

I think an `ast` query is general enough to be included in this repo.

If there is something like that please tell me.

**Comment by marijnh** [comment]
You can add a plugin to create this query type. Though you'll have to filter the `sourceFile` property from the nodes to get a sane JSON structure, and will have to do your own magic to attach types to whichever nodes you want types on.

I don't think there is an obvious portable use case or format here, so I don't think this belongs in the base library.
