### ISSUE TITLE
[ES6] modules completion for "from" throws error when * specifier is used

### ISSUE THREAD

**Issue by angelozerr** [ternjs/tern#694]
[ES6] modules completion for "from" crashes when * specifier is used

Takes the demo http://ternjs.net/doc/demo/#ES6 and do completion for from

```javascript
import * from "./ // here do Ctrl+Space"
```

It throws error `Uncaught TypeError: Cannot read property 'name' of undefined` (infer.js:1048)

**Comment by marijnh** [comment]
That was a bug in Tern's loose parser. Attached patch should fix it.
