### ISSUE TITLE
Support general metadata in the JSON type definitions

### ISSUE THREAD

**Issue by boniatillo-com** [ternjs/tern#696]
I think it is cool if we can write type definitions with general metadata. Something like:

```
{
	"MyConstructor": {
    "!type": "fn(arg: string)",
	"!metadata": {
		"custom-field": ["custom", "metadata"]
	},
    "staticFunction": "fn() -> bool",
    "prototype": {...}
  },
  "someOtherGlobal": "string"
}
```

So in queries like the `completions` query, if the user enable a `metadata` field in the query then the result will include in addition to the doc, origin, etc.. the metadata defined in the JSON type definition.

In the editor I am implementing I am doing a work around and using a separated metadata file but I think is great to have it integrated in tern and general enough to be considered... often the type systems are not descriptive enough so they are complemented by a metadata system.

**Comment by marijnh** [comment]
There is something like this already (called `!data` in JSON, and using the `metaData` property on the type or AVal), but it's not well integrated yet. If you want to look into exposing that from queries and adding tests to ensure that it works, that would be welcome.

**Comment by boniatillo-com** [comment]
Oh, good. I wish so much to have time to contribute with coding. I keep record of this issue. I want first to collaborate with tern.java then I will look here again. Thanks for your answers.
