### ISSUE TITLE
Why tern.Server doesn't load .tern-project file like command line ?

### ISSUE THREAD

**Issue by Alphapage** [ternjs/tern#699]
Hello,

As far as I know, the programming tern.Server doesn't try to get .tern-project file in the project directory.

From command line, it is able to do so and if no  .tern-project, switch to default config.

It would be great to be able to do the same with tern.Server, something like where to find the  .tern-project file and get if it uses  .tern-project or the default one.

Thanks in advance for your answers.

**Comment by marijnh** [comment]
Because it does not make assumptions about being able to access the filesystem.
