### ISSUE TITLE
Tern hangs in Firefox

### ISSUE THREAD

**Issue by mrennie** [ternjs/tern#700]
if you paste
```javascript
var a = __iterator__ = function() {};
```
into http://ternjs.net/doc/demo/#simple in FireFox and try to activate content assist, the tab will hang and you eventually will get a dialog asking to kill the script. The same snippet in Chrome (normal or Canary) works fine.

**Comment by marijnh** [comment]
Ugh. So is seems that in Gecko, adding an `__iterator__` property, even to a prototype-less object, messes up for/in iteration over that object in a way that ended up creating an infinite iteration here.

Attached patch fixes this by ignoring `__iterator__` properties on Gecko.
