### ISSUE TITLE
tern-project lib section

### ISSUE THREAD

**Issue by jrock2004** [ternjs/tern#705]
Sorry as this is not really an issue but more of a question. So in the lib section I can put jquery in there and then I will get autocomplete on the jquery functions. But how does this section work? Where is it getting the code for this? Does it look thought the project for a javscript file with the name in it? 

So lets say my project uses https://www.datatables.net/, can I just put under lib "datatables". Or does tern have a list of libraries that it supports? Thanks

**Comment by marijnh** [comment]
It gets from the `defs` directory of the Tern distribution, or from your project dir if it can't find them there. You can't just put any name there, the corresponding json file has to exist. See the [documentation](http://ternjs.net/doc/manual.html#typedef)

**Comment by jrock2004** [comment]
Does the name have to match the name of the js file?

So filename datatables.min.js

I would put in the lib -> datatables

**Comment by marijnh** [comment]
The `lib` field refers to the name of JSON files (type definitions), you can't use that to load .js files. You might want the `loadEagerly` field.

**Comment by jrock2004** [comment]
So like this

```
{
  "ecmaVersion": 6,
  "libs": [
    "browser",
    "jquery"
  ],
  "loadEagerly": [
    "bower_components/chosen/*.js",
    "bower_components/ember/*.js",
  ],
  "plugins": {
    "complete_strings": {},
    "node": {},
    "es_modules": {}
  }
}
```
