### ISSUE TITLE
property type not infered using bracket notation

### ISSUE THREAD

**Issue by aveuiller** [ternjs/tern#706]
I was trying out Tern and I found that picking a property with the bracket notation does not work when using a variable to store the property name.

You can use this snippet to reproduce the bug on the [live demo](http://ternjs.net/doc/demo/#simple):

    var obj = {
      "first": 1,
      "second": 2
    }
    // Using the dot notation will infer the type
    var typeFound = obj.second;

    // Trying the same thing using bracket notation...
    // ...will correctly find it with a string constant
    var butTypeFound = obj["first"];
    // ... but will not find the type when using a variable to store the string
    var first = "first";
    var noTypeFound = obj[first]; 

    // Trying with an array...
    var arrayTest = ["a", "b", "c", 1, 2];
    // ... will find the right type with a constant
    var typeFoundOnArray = arrayTest[2];
    // ....will give every possible type with a variable
    var arrayKey = 2;
    var typeNotFoundOnArray = arrayTest[arrayKey];

Does this problem come from a javascript limitation or is that a bug in tern? 
Is there any way of implementing this?

**Comment by marijnh** [comment]
Tern tracks only the _type_ of variables, not their content, so no, it won't be able to figure out what `obj[first]` refers to.
