### ISSUE TITLE
Implicit functions are not listed for completion

### ISSUE THREAD

**Issue by piotrtomiak** [ternjs/tern#707]
For the code below, both `fooa` and `foob` variables are hinted in completion proposals, however `fooc` is not. I think it is worth listing the function name, even if we do not know it's result type.

```javascript
fooa = 12;
foob = "ww";
fooc();
f|
```

**Comment by marijnh** [comment]
Tern looks at definitions, not uses. You never defined `fooc`, so you're not getting completions for it. That's just the way this thing works.

**Comment by piotrtomiak** [comment]
Understood. How about `fooa`, or `foob`, those are not defined as well. The definition would be with a keyword `var` or `let`, or do I miss something?

**Comment by marijnh** [comment]
Assigning to a global in JavaScript will define that global. (Well, not in strict mode, but Tern doesn't track strict/non-strict mode.)

**Comment by piotrtomiak** [comment]
Ok, thanks for the info, that was the part I was missing.
