### ISSUE TITLE
TernDef returns "TypeError: cannot read property 'url' of null

### ISSUE THREAD

**Issue by jaapz** [ternjs/tern#712]
I don't know for sure, but this is probably related to #711. See that issue for the config I am currently using.

When I import something from backbone marionette like this:

```
import {ItemView} from 'backbone.marionette';
```

And I run `:TernDef` on the `ItemView`, I get the error as described in the title.

As with the other issue, importing it with the `*` solves autocompletion and TernDef issues:

```
import * as Mn from 'backbone.marionette';
```

**Comment by marijnh** [comment]
This does indeed look like it has the same underlying cause as #711
