### ISSUE TITLE
0.17 condense regression

### ISSUE THREAD

**Issue by ramitos** [ternjs/tern#714]
Recently I tried to update my tern-dependent libs to `0.17.0`. However I noticed a regression in the condense output.

```js
var condense = require('tern/lib/condense');
var tern = require('tern');
var fs = require('fs');
var path = require('path');

var server = new tern.Server({
  async: false,
  projectDir: __dirname
});

var filename = path.join(__dirname, 'arguments.js');

server.request({
  files: [{
    name: filename,
    text: 'var arguments = 1;',
    type: 'full'
  }]
}, function(err) {
  if (err) {
    throw err;
  }
});

server.flush(function(err) {
  if (err) {
    throw err;
  }

  console.log(JSON.stringify(condense.condense(filename, filename, {
    spans: true,
    server: server
  }), null, 2));
});
```

tern 0.16.0:
```json
{
  "!name": "/Users/ramitos/dev/jsctags/arguments.js",
  "arguments": {
    "!type": "number",
    "!span": "4[0:4]-13[0:13]"
  }
}
```

tern 0.17.0:
```json
{
  "!name": "/Users/ramitos/dev/jsctags/arguments.js"
}
```

I'm going to try to find what went wrong, but this can be helpful in - most probable - case I can't fix it.

**Comment by marijnh** [comment]
We've started always normalizing file names to be relative to the project root, because absolute versus relative paths were causing confusion in the module system.

If you call `server.normalizeFilename` on your `filename`, you'll get output again. As it is, it won't match the variable's `origin` field, which will then be ignored.

**Comment by ramitos** [comment]
@marijnh I ended up not having time to look at this again, so thank you very much for you answer :wink:
