### ISSUE TITLE
Can tern be used in getting intellisense for  java script editor that is using "Avalon Edit"

### ISSUE THREAD

**Issue by Vidhyakp** [ternjs/tern#717]
I am trying to add **javascript intellisense** in **Avalon Editor** (https://github.com/icsharpcode/AvalonEdit). This is a WPF Application. 

Is it possible to use tern to achieve this. Does tern work only with js ?

**Comment by marijnh** [comment]
It's probably possible, if someone writes a plugin, but at the moment I don't think such a plugin exists.
