### ISSUE TITLE
Not creating tern files?

### ISSUE THREAD

**Issue by azer** [ternjs/tern#718]
I really wish tern to not create .tern files in my project. It pollutes my workspace and makes tern not usable for me. Is that possible ? Go's auto completing tools don't require such stuff, may be worths to re-consider tern files?

**Comment by marijnh** [comment]
It doesn't 'pollute' your workspace, it cleans up the files after it exits. Passing `--no-port-file` as a command-line arg will suppress the port file.

**Comment by azer** [comment]
@marijnh so we have to close the IDE every time we commit stuff ? because I see tern files everywhere in the directory when I'm committing.

**Comment by marijnh** [comment]
I'm not sure what version control system you're using, but I've never run across one that automatically adds all the files it finds in the source directory tree.
