### ISSUE TITLE
How to create plugin for tern for getting intellisense for java script editor that is using "Avalon Edit"

### ISSUE THREAD

**Issue by Vidhyakp** [ternjs/tern#720]
Avalon Editor is a WPF based editor.
Can some one please give an basic idea on how to build plugin for tern for AvalonEdit that supports Javascript intellisense

**Comment by marijnh** [comment]
No one here is likely to know. You can look at existing plugins, such as the one for [sublime text](https://github.com/ternjs/tern_for_sublime), and implement something similar.
