### ISSUE TITLE
Highlight and navigate through symbol occurrences on emacs module

### ISSUE THREAD

**Issue by aiguofer** [ternjs/tern#723]
I recently found http://mihai.bazon.net/projects/editing-javascript-with-emacs-js2-mode/js2-highlight-vars-mode, which allows me to easily see all instances of the variable at point and also allows me to navigate between them. This is quite convenient, and it seems like something tern could do.

My current problem with the above implementation is that it interferes with company-mode completions. Suggestions only give me about a second to tab complete before they dissappear (i'm guessing due to the 'polling' mechanism used by that plugin). I can't seem to find where I could contact that developer, so I figured I'd go ahead and make a feature request here first since I'd rather just use one tool.

**Comment by marijnh** [comment]
It is probably not too hard to implement that feature on top of Tern, but I'm not taking feature requests for the emacs mode (programming emacs is too painful), so if you want this, you'll have to work on it yourself (a pull request would be welcome).
