### ISSUE TITLE
Webpack: This plugin works only in a CommonJS environment

### ISSUE THREAD

**Issue by nikini** [ternjs/tern#727]
Hello! I keep getting `This plugin works only in a CommonJS environment` when I use webpack. My configuration is as following:

```
{
    "ecmaVersion": 5,
    "libs": [
        "browser",
        "jquery"
    ],
    "loadEagerly": [
        "resources/javascripts/**/*.js"
    ],
    "plugins": {
        "complete_strings": {},
        "doc_comment": {
            "fullDocs": true
        },
        "commonjs": {},
        "webpack": {}
    }
}
```

**Comment by marijnh** [comment]
Where are you running the code? You can't run the `webpack` plugin in the browser (or probably in any non-node environment).

**Comment by nikini** [comment]
I'm actually using [atom-ternjs](https://atom.io/packages/atom-ternjs)

**Comment by marijnh** [comment]
Yes, Electron (the Chrome shell they use) does split in-node and in-chrome scripts, and I assume Atom plugins are ran in the chrome space, and for some reason don't have direct access to node libraries.

It might be possible to find a workaround, and a patch that implements such a thing would be nice to have, but I'm not going to work on it myself.
