### ISSUE TITLE
Add Atom plugin to documentation

### ISSUE THREAD

**Issue by mikaoelitiana** [ternjs/tern#732]
Atom has a ternjs plugin and I think it should be added to editor plugins list. On github : https://github.com/tststs/atom-ternjs and on atom package list : https://atom.io/packages/atom-ternjs

**Comment by marijnh** [comment]
Want to make the changes and submit a pull request?

**Comment by mikaoelitiana** [comment]
@marijnh Yes I will do that

**Comment by mikaoelitiana** [comment]
Someone else already started it I think as I see the atom plugin link in READM now

**Comment by marijnh** [comment]
Great, I'll close this then.
