### ISSUE TITLE
Tutorial for ES6 Module resolving

### ISSUE THREAD

**Issue by fab1an** [ternjs/tern#736]
I'm testing `tern` for maybe contributing a text-mate plugin.

I don't seem to manage to make it complete imported functions though.

My `tern-project`:
```
{
  "libs": [
    "browser"
  ],
  "loadEagerly": [],
  "plugins": {
    "es_modules": {}
  }
}
```

My tested file:

```javascript
import {Controller} from "/src/util/Controller";

Controller.
````

My query:

```javascript
{
  "query": {
    "type": "completions",
    "file": "src/index.js",
    "end": {
      "line": 2,
      "ch": 11
    }
  }
}
```

Sent via curl I get: `{"start":350,"end":351,"isProperty":true,"isObjectKey":false,"completions":[]}`

**Comment by marijnh** [comment]
Is the "/src/.." path correct? It appears to be importing from `/src/` at the root of the filesystem, which doesn't look right.

**Comment by fab1an** [comment]
I resolved it, I'm passing now an absolute path to the file, which seems to work.
