### ISSUE TITLE
Emacs: Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"")

### ISSUE THREAD

**Issue by futurist** [ternjs/tern#737]
Ternjs within local `.js` file works fine.

But editing remote `.js` file on server,
using plink with Tramp mode on windows in Emacs 24.5, there's always a message as below:

````
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"")
````

The path is `C-x C-f /plink:1:/root/some-file.js`

The plink in windows using putty pre-generated key chain to connect to server(server name is 1), Dired and remote file editing & save all works fine, except this message.

**Comment by marijnh** [comment]
That error looks like it is generated by some library function that tern.el calls -- it certainly isn't throwing it itself. Are you able to get any kind of stack trace? (I must admit I forgot how to get elisp stack traces.)

**Comment by futurist** [comment]
I've open debug as below in init.el:
````
(setq debug-on-error t)
````

and the *Backtrace* window show nothing, and *Message* window has text below:

````
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"") [2 times]
Mark saved where search started
Error running timer: (user-error "Host name must not match method \"plink\"") [3 times]
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"")
Error running timer: (user-error "Host name must not match method \"plink\"")
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"")
Error running timer: (user-error "Host name must not match method \"plink\"")
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"plink\"")
````

Or, please tell me how to let ternjs to output Backtrace?

Thank you

**Comment by futurist** [comment]
When tested in MacOS 10.9.5, with ssh configured to use key chain to login remote without password both in terminal and Emacs, the message as below:

````
Error running timer `tern-reparse-on-idle': (user-error "Host name must not match method \"ssh\"")
````

I suspect it's the problem of determine `tern-project-dir` in remote, whether can provide an option to disable finding `.tern-project` remotely but only use `.tern-config` locally?

**Comment by marijnh** [comment]
Does #739 solve this?

**Comment by futurist** [comment]
tested in different platform and it's fixed. thanks for the job!
