### ISSUE TITLE
Run tern without stdin

### ISSUE THREAD

**Issue by fab1an** [ternjs/tern#740]
I'm trying to write the TextMate plugin for ternjs.
I'm looking for the `.tern-port` file and start the server if it's not found.

My problem is that tern always exits as soon as the script exits because it's stdin pipe breaks. Is there a way around this?

**Comment by marijnh** [comment]
How are you spawning the process?

**Comment by fab1an** [comment]
A TextMate command runs a ruby-script, where I fork off using

```ruby
exec(Shellwords.shellescape(File.join(TERN_DIR, 'bin', 'tern')))
```

**Comment by marijnh** [comment]
I don't have much experience with Ruby's `exec`, but most libaries allow some control over the way a process is spawned, including the way stdin/stdout are bound. This is the Python invocation used in the Sublime Text plugin:

```
  proc = subprocess.Popen(tern_command + tern_arguments, cwd=project.dir, env=env,
                          stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT, shell=windows)
```

It creates a pipe and wires it up to process. Have you research whether something like that is doable in Ruby?

**Comment by fab1an** [comment]
I researched and tried various ways. The only thing I could make work was creating a named pipe and start the server like this: `cat mypipe | bin/tern > /dev/null`

**Comment by marijnh** [comment]
That seems very Unixy and unportable. If you submit a pull request that adds an `--ignore-stdin` flag to the executable, I'll also merge that.

**Comment by vincentwoo** [comment]
+1 to this, would make ops around deploying tern in prod simpler

**Comment by fab1an** [comment]
Btw., it would be good to use something like https://github.com/substack/minimist for CLI-parsing
