### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#744]
I tend to visit files from lots of different projects that I am not in control of. In Emacs, Tern starts up every time I visit a JavaScript file. I am currently developing a plugin that could be applicable to any JavaScript code. Is there a way to say "use this plugin with this configuration in all JS files I open?"

If not, I'd like to propose a "global configuration" scheme. For instance, in my home directory, I could save a ".tern-project" file (or, more appropriately, a ".tern-config" file), and then whenever Tern starts up, it would merge a project's configuration (if any) into a copy of the global configuration object, and pass that configuration object to the server, so that my plugin could be enabled wherever I go. What do you think of this idea?

**Comment by marijnh** [comment]
If you create a `~/.tern-config` file with `{plugins: {...}}` in it, those plugins will be used for every project that doesn't specify its own `plugins` field. However, for projects that do have their own plugins configured, it will have no effect (it specifies defaults per top-level config field). Does that help?

**Comment by jacksonrayhamilton** [comment]
That does help, thanks for pointing out this feature.

Is there any reason not to merge the fields? Disabling global plugins simply because other plugins are present could be inconvenient if I ever encounter a project with a `.tern-project` file committed. (Granted, maybe it is unwise to commit `.tern-project`, because it is used by an optional tool, and therefore a subset of developers, each who may wish to personalize the configuration to his liking.)

**Comment by marijnh** [comment]
> Is there any reason not to merge the fields? 

Not really, except that I didn't bother. Attached patch fixes this.

**Comment by jacksonrayhamilton** [comment]
Works great!
