### ISSUE TITLE
Please update your list of plugins!

### ISSUE THREAD

**Issue by JeffOwOSun** [ternjs/tern#745]
I was looking for something to support `import` clauses in my webpack-enabled project. I wen through the vague descriptions in http://ternjs.net/doc/manual.html#plugins but found no clue. I googled 'tern webpack' and saw the webpack.js plugin but it didn't help.

After hours of reading through the code without success, I stumbled across the documentation for atom-ternjs, which mentioned `es_modules`. But it's **nowhere to find in the documentation**! It could have been a lot easier had there been just a few lines mentioning it.

BTW, great job with this project.

**Comment by marijnh** [comment]
The module _is_ mentioned in the manual, it just didn't include its filename. That's fixed with attached patch.
