### ISSUE TITLE
vy plugin

### ISSUE THREAD

**Issue by iogf** [ternjs/tern#748]
Vy has a javascript plugin that uses tern.

https://github.com/iogf/vy/blob/master/vyapp/plugins/javascript_completion.py

I think it should be added to the list of editors that use tern.

**Comment by marijnh** [comment]
Pull request?

**Comment by iogf** [comment]
what do you mean with pull request?

**Comment by marijnh** [comment]
Could you make the changes and then use github to submit them?

**Comment by iogf** [comment]
Yes. I have made the changes to the manual.txt then generated a new manual.html. Is that okay? But that will not be enough to have vy listed in the main page of ternjs.net though. it will be listed only in the manual.html.
