### ISSUE TITLE
update tag to 0.18.1

### ISSUE THREAD

**Issue by maruilian11** [ternjs/tern#752]
hi, recently we want to add your lib on https://cdnjs.com, could you please update your tag after every releasing so that we can update the lib to the latest version with **git auto-update config**.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7451

**Comment by marijnh** [comment]
What kind of tag are you talking about? If you mean git tags, 0.18.1 is not a release, just a dev version, so you don't want that on your CDN.

**Comment by maruilian11** [comment]
thanks.
