### ISSUE TITLE
Show datatype name instead of the full type description

### ISSUE THREAD

**Issue by Binjaaa** [ternjs/tern#753]
Hey!

I have a function which has a resultData parameter with the type of DataView. This looks like the following in the code completion tooltip.

`resultData: fn(buffer: +ArrayBuffer, byteOffset?: number, byteLength?: number)`
My preffered code completion would be:

`resultData: DataView`

Is that somehow managable?

**Comment by marijnh** [comment]
Not really. Tern doesn't use type names when showing function types, because those would usually be unhelpful.

**Comment by Binjaaa** [comment]
Thx @marijnh !
