### ISSUE TITLE
Renaming directory with Dired causes errors

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#756]
Emacs version: 25.0.92.1
Tern version: 0.18

With the following file:

`/Users/Jackson/test/tern-1/foo.js`:

```js
var a = 5;
a;
```

When I use Dired to rename the directory `tern-1` to `tern-2` containing `foo.js` while it is in an open buffer and that has been analyzed by Tern, the Emacs plugin starts to malfunction.

It is unable to find the definition of the second `a` when I ask for it, and eventually an error gets printed "Error running timer ‘tern-reparse-on-idle’: (file-error "Setting current directory" "No such file or directory" "/Users/Jackson/test/tern-1/")".

Also, `.tern-port` is created in that `test/tern-1` directory.

I guess the Emacs Tern plugin or the server doesn't realize its directory has been renamed? I wonder if it is possible for the plugin or the server to be pessimistic about the locations of their files.

**Comment by marijnh** [comment]
Tern-mode keeps some buffer-local state (`tern-project-dir` is the most likely culprit) that it doesn't know to automatically update in such a case. If you want to try and fix this, that'd be great, but I don't have time to work on it myself.
