### ISSUE TITLE
Unexpected completion proposals

### ISSUE THREAD

**Issue by mrennie** [ternjs/tern#757]
Enter the snippet: `var foo = /f*/;` in the Tern demo and activate content assist immediately following the first `/`. You get three proposals, where I would expect to get none - since we are inside a regex literal and the proposals are not related to a regex literal.

**Comment by marijnh** [comment]
Tern doesn't require you to be in a specific type of token to return completions -- if you ask for completions, you get them, based on the scope of your cursor. This seems preferable to denying requests, since there are valid situations in which you'd want completions pretty much in every context.
