### ISSUE TITLE
arguments (incorrectly?) in arrow function scope props

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#758]
It seems like a scope object whose `originNode.type` is `"ArrowFunctionExpression"` has a `props` object with a key of `arguments`. But arrow functions do not have their own `arguments` object, it comes from an enclosing `function`. From the spec: http://www.ecma-international.org/ecma-262/6.0/index.html#sec-arrow-function-definitions-runtime-semantics-evaluation

> Any reference to arguments, super, this, or new.target within an ArrowFunction must resolve to a binding in a lexically enclosing environment.

So I think this is a bug, and an `arguments` appearing in an ArrowFunctionExpression should instead be in the `props` of the closest enclosing `function`, if any.

**Comment by jacksonrayhamilton** [comment]
Could you double-check if this is fixed? I am still seeing `arguments` on an arrow function's `props` with the following code snippet:

```js
(function () {
  (() => {
    arguments;
  });
});
```

**Comment by marijnh** [comment]
I made a typo. Fixed in f9924b3
