### ISSUE TITLE
Multiple environments

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#760]
Right now, it seems like enabling the `es_modules` and `node` plugins will cause all files in a project to be treated as modules, and in the case of `node`, the environment will have Node.js globals and free variables.

I have projects in which there is more than one JS environment. Some code is browser script code and other code is Node.js modules, and I don't want these files to share the same scoping rules and variables. The only way I know of ensuring correct environment settings is to separate my code into directories corresponding to its environments and create additional `.tern-project` files in those directories to enable only the plugins I need. But I can see this being a tedious or invasive organizational requirement.

I think we could remove this organizational requirement by applying plugins more selectively. Here are some ideas I had:

- Offer to restrict plugins to certain files; globs could be specified in `.tern-project` to include / exclude files from a plugin's reach.
- Scan code for configuration comments like `/* tern-plugins es_modules, node */` to enable plugins on a per-file basis (this is what JSHint, JSCS and ESLint do).
- Offer to guess if a plugin should be used; e.g. `es_modules` could search for an `import` or `export`, `node` could search for `module.exports` or `#!/usr/bin/env node`, etc. (I actually [wrote some logic](https://github.com/jacksonrayhamilton/tern-context-coloring/blob/75d79022c90bd1230d4ae6576cd407d9c60c2a5b/scopify.js#L158) to do exactly this in another project, but have since removed it from that project due to it not really belonging there.) This approach would be less reliable and potentially slower (due to maybe requiring extra parses), but it could potentially be more convenient for users.

**Comment by marijnh** [comment]
Note that it's not just about picking the right plugins -- it's about picking the right Tern server, so that files that are supposed to be a single project can see each other. As such, your proposals 2 and 3 wouldn't really work.

**Comment by jacksonrayhamilton** [comment]
Are you referring to how plugins are currently applied server-wide? I guess I assumed that some aspect of plugin infrastructure / behavior would have to change to effect these proposals (the extent of which is not entirely clear to me).

**Comment by marijnh** [comment]
Yes. A server represents an execution environment, and Tern assumes that every file is loaded in the same way in such an environment.

**Comment by jacksonrayhamilton** [comment]
I see; and by "a server," I assume you mean "an instance of `tern.Server`."

In that case, here's an idea for how that could be supported: `.tern-project` could permit a JSON array of configuration objects. These objects would represent configuration for separate instances of `tern.Server`, "scoped" to a set of files matching a glob pattern specified in each object. When a query specifies a `file`, the HTTP request handler could determine which server to send the request to.

A problem with this is that not all queries require a `file` property. We might need to either "pick one" or combine a set of results from the servers, neither of which sound like good solutions. Ultimately we'd probably want to update the API to mandate `file`.

**Comment by jacksonrayhamilton** [comment]
Handling multiple environments would probably be too complicated, and it hasn't been a big issue for me lately, so closing.
