### ISSUE TITLE
Option to treat shebang / hashbang as a comment

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#762]
Acorn has an option `allowHashBang` to treat `#!` as a comment. I was considering writing a little plugin to enable this, but I realize it'd be such a simple feature that it might better suited in Tern itself. Do you think we should have a way to turn this on?

**Comment by marijnh** [comment]
Doesn't the error-tolerant parser already mostly solve this? I've never had trouble getting Tern completions in hashbang files.

**Comment by jacksonrayhamilton** [comment]
Yeah, the parser does make this pretty benign. Here's one scenario I came up with:

```js
#!/usr/bin/env node
var env;
```

Rename `env` to `environment`, and the shebang will program will also get renamed.

The shebang also gets colored kind of funny in my plugin, tern-context-coloring (because it thinks it found global variable references):

<p align="center"><img alt="funny shebang coloring in tern-context-coloring" src="https://shareitdammit.com/aCGleidg"></p>

**Comment by marijnh** [comment]
That's a good point. Attached patch passes the relevant option to Acorn (by default, seems like you wouldn't really need to opt out of that).
