### ISSUE TITLE
Deleted files still appear in module list

### ISSUE THREAD

**Issue by vincentwoo** [ternjs/tern#768]
Recently, while playing around with adding precondensed module types, I inserted this line:

(in modules.js)
```js
      infer.def.load(override, scope)
      return this.modules[name] = scope.exports
    },

    resolveModule: function(name, parentFile) {
+     console.log(this.modules);
      var over = this.maybeOverride(name)
      if (over) return over
      var known = this.knownModules[name]
```

and logged the output after a few file additions and deletions:

```
{ 'node_modules/underscore/underscore.js':
   { types: [ [Object] ],
     forward: [ [Object], [Object], [Object], [Object] ],
     maxWeight: 100,
     origin: 'node_modules/underscore/underscore.js' },
  '5.js':
   { types: [ [Object] ],
     forward: null,
     maxWeight: 100,
     origin: '5.js' },
  '6.js':
   { types: [ [Object] ],
     forward: null,
     maxWeight: 100,
     origin: '6.js' },
  '7.js':
   { types: [ [Object] ],
     forward: null,
     maxWeight: 100,
     origin: '7.js' },
  '8.js':
   { types: [ [Object] ],
     forward: null,
     maxWeight: 100,
     origin: '8.js' } }
```

For references, 5.js through 8.js were all files added and deleted via API. It looks like tern is still retaining references to them, at least in the Modules class.

**Comment by marijnh** [comment]
Yes, plugins don't typically clean up with regard to deletion until the next context reset (which the server automatically schedules, but which you can force with the `.reset()` method). This is done intentionally to reduce complexity.
