### ISSUE TITLE
Doc comments not picked up with ES2015 export statement

### ISSUE THREAD

**Issue by akim-mcmath** [ternjs/tern#769]
Tern doesn't seem to pick up the JSDoc comment in the following case:

```js
/**
 * Divides one number by another.
 *
 * @param   {number}  x  Numerator.
 * @param   {number}  y  Denominator.
 * @return  {number}     Quotient.
 */
export function divide(x, y) {
  return x / y;
}
```

It behaves just as if the comment wasn't there. It recognizes the `divide()` function as an export,
but it doesn't get the description and type information from the comment.

Oddly, however, the following works fine:

```js
/**
 * Divides one number by another.
 *
 * @param   {number}  x  Numerator.
 * @param   {number}  y  Denominator.
 * @return  {number}     Quotient.
 */
function divide(x, y) {
  return x / y;
}

export {divide};
```

Is this a bug, or am I missing something?

**Comment by marijnh** [comment]
Fixed in 453f6fd

**Comment by akim-mcmath** [comment]
@marijnh Thank you very much for this, and for your work on this fantastic project.

**Comment by alisd23** [comment]
Having the same issue with v0.21.0, except with variable declarations:

The following does not recognise the typing of `someString`
```js
/** @type {string} */
export let someString;
```

Yet this does:
```js
/** @type {string} */
let someString;
export someString;
```
