### ISSUE TITLE
tern crashes on 'export * as foo from "foo"'

### ISSUE THREAD

**Issue by alexsaveliev** [ternjs/tern#772]
#### how-to-repeat

- open http://ternjs.net/doc/demo/index.html#simple
- enter the following snippet
```
export * as foo from "foo";
```
- hit ctrl+space

#### actual result

```
walk.js:36 Uncaught TypeError: Cannot read property 'type' of null
```

#### expected result

there should be no error

**Comment by marijnh** [comment]
That was an issue in Acorn. Attached patch fixes it.
