### ISSUE TITLE
node plugin: outdated defs

### ISSUE THREAD

**Issue by alexsaveliev** [ternjs/tern#775]
There are some defs that are outdated, for example:

- `console` module uses wrong URL (https://nodejs.org/api/stdio.html#....) while current one look like (https://nodejs.org/api/console.html#....)
- `events` module uses wrong hashes, for example https://nodejs.org/api/events.html#events_class_events_eventemitter while expected https://nodejs.org/api/events.html#events_class_eventemitter

**Comment by marijnh** [comment]
Want to submit a pull request to fix these?

**Comment by alexsaveliev** [comment]
okay, will do
