### ISSUE TITLE
files hosted on `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [ternjs/tern#783]
hi, recently we want to host your lib on https://cdnjs.com, i want to confirm if these files
`lib/+(comment*|condense*|def*|infer*|signal*|tern*).+(js|map)`  
`plugin/+(angular*|commonjs*|complete_strings*|doc_comment*|es_modules*|modules*|node*|node_resolve*|requirejs*|webpack*).+(js|map)`
are also need to be hosted.
especially, are `node.js` and `node_resolve.js` for nodejs? 
thank you very much!

https://github.com/cdnjs/cdnjs/pull/7566#discussion_r59859126
https://github.com/cdnjs/cdnjs/issues/7451

**Comment by marijnh** [comment]
The [manual](http://ternjs.net/doc/manual.html#plugin_node) might help.
