### ISSUE TITLE
Microsoft Language Server Protocol

### ISSUE THREAD

**Issue by sevin7676** [ternjs/tern#799]
Any plans on making Tern compatible with Microsoft's new [language server protocol](https://github.com/Microsoft/language-server-protocol)? 

I might have a go at it myself if I ever get some more free time.

**Comment by marijnh** [comment]
Nope, no plans. You can write a wrapper. It is very unlikely that we'll adjust our base protocol to this.

**Comment by prabirshrestha** [comment]
@marijnh Given that it has been more than a year wondering if you guys have changed your thoughts on LSP? I have created [vim-lsp](https://github.com/prabirshrestha/vim-lsp) plugin which works in both vim8 and neovim and is async. I currently use it for typescript and it has been working very well. Before I go ahead and create LSP wrapper like I did for [typescript-language-server](https://github.com/prabirshrestha/typescript-language-server) wondering if this is in roadmap or if you would be open to accepting PRs after more discussions. If not I have been planning to create LSP wrapper like I did with typescript as a separate project and in future we can again revisit about merging it in tern if it proves useful.

**Comment by marijnh** [comment]
Still the same -- I don't want to expand the scope of the library, but it should be modular enough to use as a base for writing an LSP server.

**Comment by prabirshrestha** [comment]
Thanks. I just wanted to know whether I should be send PRs here to create my own repo. I will update once again when I have some more progress.

**Comment by boniatillo-com** [comment]
I vote for this, ternjs is a great engine that I really miss on LSP enabled editors.

But @marijnh is right, an LSP implementation should be provided by a third-party project.

**Comment by tbodt** [comment]
I made one: https://github.com/tbodt/js-langserver. It only does completions for now, even though renaming etc is possible. I'll probably add go to definition soon.

It also lints with eslint, in case you want that too. (Currently no way to turn that off...)
