### ISSUE TITLE
Bump version for sake of plugin

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ternjs/tern#802]
My plugin [tern-context-coloring](https://github.com/jacksonrayhamilton/tern-context-coloring) currently has [a few failing tests](https://travis-ci.org/jacksonrayhamilton/tern-context-coloring/builds/143575429) on `0.18.0` related to bugs that were fixed on `master`: https://github.com/ternjs/tern/pull/754, https://github.com/ternjs/tern/issues/758. I'd like to add a "build passing" badge, and simplify my documentation, which currently instructs to install the git version of Tern, which is awkward. So, would you be willing to bump the npm package version?

**Comment by marijnh** [comment]
Definitely. I've released version 0.19.0

**Comment by jacksonrayhamilton** [comment]
Thanks!
