### ISSUE TITLE
How to know all subtypes of an object using Tern

### ISSUE THREAD

**Issue by sosahvictor** [ternjs/tern#808]
I want to get all subtypes of a given object in an Eclipse project using Tern. I've been looking at Tern.java but all I see is tooling for context inference within the same JavaScript file as well as plugins hooked in .tern-project. This is not enough for what I can read to know the subtypes of a given object in a project.

My next approach is to create my own plugin that could use Tern's inference engine in order to extract that type hierarchy. It has decent documentation about how to extract the AST from a set of files. However, for all I can read in the documentation, there's no straight forward way to pull out the type hierarchy. 

My question, is there an existing plugin that can achieve this or how can I use Tern's inference engine to achieve it?

https://github.com/angelozerr/tern.java
http://ternjs.net/doc/manual.html#infer

**Comment by angelozerr** [comment]
@sosahvictor I think you wish to fill "Hierachy View" Eclipse and support too "Find Type". To do that you must create a tern plugin.

Just one question, have you the intention to contribute to tern.java?

**Comment by piotrtomiak** [comment]
In Webclipse JSjet, which is Eclipse plugin based among others on Tern.java, you can get Type Hierarchy (software is free for any 8 days per month). It utilizes tern.js inference engine. Tern is really cool for content assist, but has some shortcuts and nuances when it comes to exposing types. It was quite a challenge to extract this information from it and if you are not planning to get dirty with Tern source code I wouldn't advise starting the topic ;)

**Comment by sosahvictor** [comment]
@piotrtomiak The idea is to have our own tool that can do this with no dependency to other third-party than ternjs and tern.java

@angelozerr This didn't come through my mind. I cannot make any promise as I need to discuss it with my manager, but at least I can bring it to the table and see what happens.

BTW, I was looking at tern.outline and that's how I realized I need to create my own tern plugin. Any pointer about how to accomplish this? As Piotr mentions, it seems that in order to enhance ternjs you need to really get your hands into the dirt which seems bad if it's supposed to provide an API for this purpose.

**Comment by marijnh** [comment]
This is out of scope for Tern itself, but as mentioned, it should be possible to do it in a plugin.
