### ISSUE TITLE
yui compressor cannot compress infer.js (latest version) due to errors.

### ISSUE THREAD

**Issue by jgoldhammer** [ternjs/tern#816]
Can you please check this?

``
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [1315:34]: missing name after . operator
[ERROR] ...infer.js:line 1315:column 34:missing name after . operator
	          target = (method.static ? fn : proto).defProp(pName, method.key)
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [1316:18]: syntax error
[ERROR] ...infer.js:line 1316:column 18:syntax error
	          target.initializer = true
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [1317:43]: missing ; before statement
[ERROR] ...infer.js:line 1317:column 43:missing ; before statement
	          if (method.kind == "get") target = new IsCallee(inst, [], null, target)
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [1324:6]: syntax error
[ERROR] ...infer.js:line 1324:column 6:syntax error
	    })
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [2159:3]: missing } after function body
[ERROR] ...infer.js:line 2159:column 3:missing } after function body
	});
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [2159:3]: missing } after function body
[ERROR] ...infer.js:line 2159:column 3:missing } after function body
	});
[ERROR] /Users/jgoldhammer/development/sources/js-console/javascript-console-share-aikau/src/main/amp/web/js/javascript-console/tern/lib/infer.js [1:0]: Compilation produced 6 syntax errors.
[ERROR] ...infer.js:line 1:column 0:Compilation produced 6 syntax errors.
``

Thanks,
Jens

**Comment by marijnh** [comment]
The YUI compressor is an outdated piece of junk, and I'm not really interested in supporting it. Consider using UglifyJS or any other compressor whose authors actually understand parsing.
