### ISSUE TITLE
Tern server is unable to recover from reset

### ISSUE THREAD

**Issue by krogank9** [ternjs/tern#819]
On line 167 of tern.js:

``` javascript
if (self.uses > 40) {
  self.reset();
  analyzeAll(self, null, function(){});
}
```

The server is reset after its uses reaches 41, which is incremented when a file is pushed. The problem is, some files only analyze correctly the first walk through their AST and not the second walk through it. This causes some files to be analyzed wrongly and stop displaying proper types and completions after 41 requests when the AST's are reanalyzed.

Here's a node script that demonstrates the breaking: http://pastebin.com/t1VQzwhu
And the javascript file whose AST isn't analyzed correctly the second time: http://pastebin.com/DMXpWFjX 
Output: http://pastebin.com/CY8C09rV

If the file's AST is reparsed from its text before the second analysis, it works fine. This suggests that the first walk through the AST by analyzeFile() breaks the AST in some way. Upon further investigation, after tern's first analysis, it voids any functions that define other functions inside of themself, this breaks it after 41 requests:

``` javascript
var Apple = {};
function a(Apple) {
  function(){};
  Apple.color = 'red';
}
a(Apple);
```

Unless the functions are assigned to something or returned immediately. So this works fine:

``` javascript
var Apple = {};
function a(Apple) {
  var unused = function(){};
  Apple.color = 'red';
  return function(){};
}
a(Apple);
```

If i set the scope of function a()'s  body to null in the AST the second analysis works fine. Actually, I can't get any function in an AST to analyze correctly unless the body's scope is undefined/null. When returning or setting the function equal to something the body's scope will still be set to null. So tern breaks when any function has a body with a scope. I see in tern.js you set all the file's scope to null. Maybe you didn't think of the case that functions could have a scope too and those should also be set to null on reset? scopeGatherer is doing something funky to scope of function body's on its second walk through the tree which is preventing the constraint gathering pass from working right. Maybe the body isn't even supposed to have a scope at all? I'm pretty unfamiliar with this project but I'm trying to figure out the bug. Hopefully someone who knows more can drop in and help.

When I console.log the functions scopes, I see that before the second analysis they are circular, but afterwards, the circular references disappear and it's just regular object references. I guess it's referring to scope on the old AST and it doesn't get changed to the new one on the second analysis after the reset?

**Comment by krogank9** [comment]
OK I believe I found the cause of the bug on line 1116 of infer.js where it says:
```javascript
BlockStatement: function(node, scope, c) {
  if (!node.scope && node.body.some(isBlockScopedDecl))
    scope = node.scope = new Scope(scope, node, true)
  walk.base.BlockStatement(node, scope, c)
},
```
a new node.scope is created if one isn't already. If the !node.scope part is removed so as to define a new scope on each scope-gathering walk the problem goes away. I guess the old scope is being kept when it shouldn't be and thus causing inconsistency in the tree because the references aren't circular and maybe it refers to the old tree's scope instead of the current? Why even keep the old scope if we're walking through it all again anyway? Am I missing something here or is this just an error?

**Comment by krogank9** [comment]
So is tern dead? I would at least like a reply. I was working on an editor plugin but stopped because of this bug. I did my best to clearly describe the problem but I don't know the ins and outs of tern. I'm sure if someone who did would read this it would be an easy fix.

**Comment by marijnh** [comment]
Tern isn't a big priority for me right now, but please save me the 'dead' rhetoric. It's used daily by me and many others, and there's been patches merged this very week.

As for your problem, I am not sure what's going on there. ASTs are supposed to be read-only, and scopes are entirely determined by the AST's shape, so I don't understand how a scope object can be outdated.

**Comment by krogank9** [comment]
Have you tried it with the script I provided? It's 100% reproducible every time. Fails after self.uses reaches 41.

http://pastebin.com/t1VQzwhu

This is the file it fails with.
```
var Apple = {};
function a(Apple) {
  function(){};
  Apple.color = 'red';
}
a(Apple);
```

**Comment by marijnh** [comment]
Ah, the global scope is indeed recreated when re-analyzing. Sorry, it's been a while since I worked with that code. Does attached patch help?

**Comment by krogank9** [comment]
Yep. Thanks. Now it works great.
```
computer@computer:~$ ./test_node 
All queries work as normal:
Response: {
  "type": "fn(type: ?) -> string",
  "name": "Food.Eat",
  "exprName": "Eat",
  "origin": "myfile.js"
}

Sending 41 requests. . . 

Now the server is broken. 42nd request:
Response: {
  "type": "fn(type: ?) -> string",
  "name": "Food.Eat",
  "exprName": "Eat",
  "origin": "myfile.js"
}
```
I guess we were using different js libraries and setups but it used to break all the time. I think that patch will fix it for a lot of people.
