### ISSUE TITLE
It's impossible to register plugins when tern server is loaded as AMD module

### ISSUE THREAD

**Issue by PavelSosin** [ternjs/tern#824]
I'm loading TernJS server in my own Dev Environment inside WebWorker as a AMD module using the following code:
__function startServer(defs, plugins, scripts) {
	var ternPath =  'lib/tern.js';
	require.config({
		baseUrl: ".",
		paths: {
			'acorn': 'acorn',
			'plugin': 'plugin'
		}
	});
	var that = { defs: defs, plugins: plugins, scripts: scripts };
	require([ternPath], function(_tern) {
		that.tern = _tern;
		require(that.scripts, function() {
			
		  server = new that.tern.Server({
		    getFile: getFile,
		    async: true,
		    defs: that.defs,
		    plugins: that.plugins
		  });		
			
		});
	} );_
}_

In this case registerPlugin() method doesn't work because plugins variable (declared at line 17 of tern.js ) is assumed to be global.

**Comment by marijnh** [comment]
The `plugins` variable in tern.js is local to that module. I don't know what you're trying to do here, but you definitely don't need to touch that variable.
