### ISSUE TITLE
Can not get tern to install globally on Windows 10

### ISSUE THREAD

**Issue by computersarecool** [ternjs/tern#828]
Hi,

I am running Windows 10 and emacs 24.5.1 (through Cygwin).

I have read all of #256 and I have what I think is a (much) smaller issue.  I seems like I just can't get tern installed globally correctly.

When I check `C:\Users\myusername\AppData\Romainig\npm` I see all of the other globally installed npm packages but nothing related to tern.

I do see tern inside the `C:\Users\myusername\AppData\Romainig\npm\node_modules` directory, but when I run `tern` from the command line I get:

`'tern' is not recognized as an internal or external command`.  (even if I am in that folder). 

If, through Cygwin, I cd into that directory, I can run `tern`  (it just says listening on port...).  However, when I try to run a `.js` file, in emacs I get:

`File mode specification error: (file-error "Searching for program" "no such file or directory" "tern")`

I even went so far as to add  `C:\Users\myusername\AppData\Romainig\npm\node_modules\tern` to my path but this made no difference.  I would really appreciate any help.

Thanks

**Comment by marijnh** [comment]
You could set the `tern-command` variable in Emacs to `"C:\Users\myusername\AppData\Romainig\npm\node_modules\tern\bin\tern"`.

**Comment by computersarecool** [comment]
When I run that I now get:

`Error running timer `tern-reparse-on-idle': (wrong-type-argument stringp 99)`

**Comment by marijnh** [comment]
Sorry, yes, it has to be a list, so `'("C:\Users\myusername\AppData\Romainig\npm\node_modules\tern\bin\tern")`

**Comment by computersarecool** [comment]
Sorry to be such a bother. But that gave me this error:
```
Request failed: Could not start Tern server
module.js:339^M
    throw err;^M
    ^^M
^M
Error: Cannot find module 'C:\cygdrive\c\Users\willy\AppData\Romaning\npm\node_modules\tern\bin\tern'^M
    at Function.Module._resolveFilename (module.js:337:15)^M
    at Function.Module._load (module.js:287:25)^M
    at Function.Module.runMain (module.js:467:10)^M
    at startup (node.js:134:18)^M
    at node.js:961:3^M
```

**Comment by computersarecool** [comment]
My sincerest apologies.  This was due to an error in my `PATH` on Windows.  Correcting that and reinstalling tern makes it work.

**Comment by gil-air-may** [comment]
@computersarecool I seem to be facing the exact same issue. What kind of error in yout PATH were you facing?
