### ISSUE TITLE
[emacs plugin] Doesn't autocomplete multiple file

### ISSUE THREAD

**Issue by Sgregory42** [ternjs/tern#829]
Hi,

First of all I am no javascript/node.js expert, I am more of a C++ dev.

I am using spacemacs with the javascript layer that include tern.
Here is my testing project : https://github.com/Sgregory42/tern_debug
This project is used by this game https://screeps.com/ so I don't run anything on my machine.
But what I want, is the autocompletion of their library (which is the folder lib) and also of my files.

It seems that even with loadEargly variable tern doesn't seems to load the  file of my project.
I tried loadEargly with "./\*.js" and "*.js" format but didn't make  a difference.
 
- If I open just the main.js I can't autocomplete something in other file.
- But if I open a file in a buffer tern does recognize it as a file and I can autocomplete it
- Tern seems not to recognize global variable (ex : trying to autocomplete the Game variable in lib/Game.js from main.js)

I've been on this for a week and no one seems to know what is the problem. 

Could you please advice ? Thanks

ps : is there a way to request the list of files from tern ? seems like I need to send a request with the type variable but I couldn't make it work.

**Comment by marijnh** [comment]
What does your .tern-project config file look like? Are you loading any module system plugin?

**Comment by Sgregory42** [comment]
Here is it : 
{
  "libs" : [
          "lodash"
          ],
    "ecmaVersion" : 6,
    "loadEagerly": [ "*.js",  "lib/*.js" ],
    "plugins" : {
	"node" : {} 
    } 
}
As I said tried "./*js" too.
Thanks for you fast reply.

**Comment by marijnh** [comment]
The `node` plugin will cause files to be treated as CommonJS modules, so variables declared at the top scope will not be treated as globals. Could that be your issue?

**Comment by Sgregory42** [comment]
I remove the node plugin, doesn't seems to solve the issue.

```
{
  "libs" : [
          "lodash"
          ],
    "ecmaVersion" : 6,
    "loadEagerly": [ "*.js",  "lib/*.js" ],
    "plugins" : {
    } 
}
```

**Comment by marijnh** [comment]
If I rename `config.tern-project` to `.tern-project` in that git repository, remove the `"node"` line, and open `role.hauler.js`, I get working completions if I type something like `Cr`. (This is on regular Emacs, but Spacemacs should be the same I think)

**Comment by Sgregory42** [comment]
I am at work, I'll give it a try this evening and keep you updated.  Thanks

**Comment by Sgregory42** [comment]
Awesome it works ! I didn't expect to have a problem with the name of the config file.

Quick question :
In Game.js, the Game object has a property "creeps" of type \{Array\<string, Creep\>\} : 
```
Game = {
 ...
    /**
     * A hash containing all your creeps with creep names as hash keys.
     *
     * @type {Array<string, Creep>}
     */
    creeps: {},
...
}
```
If I do `Game.creeps["RandomName"].upgrade` it will autocomplete to any method/property of any object that has "upgrade".
Is it possible to only have the ones of the Creep object since the Game.creeps return a Creep object ?

Thank you very much !

**Comment by marijnh** [comment]
I'm not sure what `Array<string, Creep>` means in JSDoc, but for Tern that'd be a value like `["foo", new Creep]`, which it definitely isn't since it's initialized as `{}`. You could say `Object<Creep>`, I think that'll work.

**Comment by Sgregory42** [comment]
Sorry, could you please clarify ?
I am not fully familiar with javascript syntax
Thanks

**Comment by marijnh** [comment]
The documentation. Tern will pick up the @-annotated doc comments as type hints. You could try replacing `Array<string, Creep>` with `Object<Creep>`.
