### ISSUE TITLE
'This' properties inside Polymer objects

### ISSUE THREAD

**Issue by richardsd** [ternjs/tern#830]
Hi,
I am trying to make a plugin for Tern to be able to support autocompletion inside Polymer elements.
At the moment I am able to access the properties that have been directly declared, but not the ones inside the defs.json I have created.

Assuming I have something like this:

```
'!name': 'polymer',
'Polymer': {
  '!type': 'fn(config: +Polymer.Base) -> +Polymer.Base',
  'Base': {
    '!type': '+Polymer.Base',
    'prototype': {
      'set': {
      '!type': 'fn(path: string, value: ?)',
      '!doc': 'Convenience method for setting a value to a path and notifying any elements bound to the same path.'
},

```
I would like to be able use this.set() inside a Polymer.Base element. Do you have any idea how can I accomplish this? I think that the problem is the prototype of the 'this', because it is not 'Polymer.Base', but I am not sure how can I do it.

**Comment by marijnh** [comment]
Please don't [repost](https://discuss.ternjs.net/t/this-properties-inside-polymer-objects/70) the same thing in two places

**Comment by richardsd** [comment]
Sorry for the repost, I was going nuts on this topic, still trying to figure if it is even possible to do this.
