### ISSUE TITLE
Custom angular factories not populating

### ISSUE THREAD

**Issue by tandrewnichols** [ternjs/tern#847]
I'm using YouCompleteMe in conjunction with tern_for_vim to get code completion. I have the following `.tern-project` file in the root of my project: 

```
{
  "libs": [
    "browser",
    "jquery",
    "underscore"
  ],
  "plugins": {
    "node": {},
    "modules": {},
    "angular": "./client/app/js"
  }
}
```

This _sort of_ works. If I'm editing an angular file in `client/app/js/` that injects a built-in service, like `$http` for example, I get autocompletion after `$http.` (e.g. `post`, `delete`, etc.). But if I inject a custom Service, I get nothing. Example:

```
// Factory in client/app/js/services/foo.js
angular.module('app').factory('Foo', function() {
  var service = {
    fn: function() {}
  };
  return service;
});

// Controller that uses Foo in client/app/js/controllers/bar.js
angular.module('app').controller('Bar', function($scope, $http, Foo) {
  $scope.| // <-- I get completion for this based on what's in this file, but not built in things like $eval
  $http.| // <-- I get full completion for this
  Foo.| // <-- I get nothing here
});
```

Am I doing something wrong or is something functioning in an unexpected way?

**Comment by marijnh** [comment]
`factory` isn't a method the Tern angular plugin supports. Was it added in a recent version?

In any case, this plugin isn't being extended or actively maintained anymore. If you submit a pull request, I'll look into it, but I'm not adding features myself.

**Comment by tandrewnichols** [comment]
Factory and service are essentially the same, except that factory is a singleton and service is called with `new` every time. As far as I know, it's been around. We're using Angular 1.2, which is not really new.

Thanks for the quick feedback. Are you saying "the Tern angular plugin" or tern itself isn't being extended or actively maintained?

**Comment by marijnh** [comment]
The plugin

**Comment by tandrewnichols** [comment]
Gotcha, thanks

**Comment by tandrewnichols** [comment]
Not trying to drag this out. I _do_ understand the meaning of "not actively maintained." There _are_ references to `factory` in the angular plugin, like [this one](https://github.com/ternjs/tern/blob/master/plugin/angular.js#L821).

**Comment by marijnh** [comment]
Oh, you're right, I grepped incorrectly before. There's even a test exercising it, which is passing, so it _kind of_ works, at least.
