### ISSUE TITLE
Please add methods.

### ISSUE THREAD

**Issue by yaphtes** [ternjs/tern#850]
Hello.
Can you add next methods?
`Element.prototype.append();`
`Element.prototype.prepend();`
`Element.prototype.before();`
`Element.prototype.after();`

I don't know `prototype`, maybe is:
`Node.prototype.append();`
`Node.prototype.prepend();`
`Node.prototype.before();`
`Node.prototype.after();`

**Comment by marijnh** [comment]
Could you submit a pull request?

**Comment by yaphtes** [comment]
no i can`t, because i am new member in github.
UPD: plese, add methods, elem.matches() and elem.closest()
links in mdn: https://developer.mozilla.org/en/docs/Web/API/Element/closest and https://developer.mozilla.org/en/docs/Web/API/Element/matches

**Comment by mrennie** [comment]
I can submit a PR for this. Just one question though, how do you represent varargs in an index?

For example, the API doc for append(...) is a list of strings or nodes. So would the index type look like: `fn(nodes: string|Node?)`

**Comment by yaphtes** [comment]
I think your API doc is well suited. 👍

**Comment by marijnh** [comment]
You should be able to write a type like `fn(...nodes: [string | Node])`
