### ISSUE TITLE
Feature request: code completion: case-sensitive only for first letter.

### ISSUE THREAD

**Issue by lixiaoyan** [ternjs/tern#851]
https://www.jetbrains.com/help/webstorm/2016.2/code-completion.html

> - All: The lookup list includes only those items that match the case of all typed letters. This option is most restrictive.
> 
> ![image](https://cloud.githubusercontent.com/assets/1610614/19831736/12b2df30-9dd7-11e6-8d33-31f252dff26c.png)
> - None: The lookup list includes all matches regardless of their case.
> 
> ![image](https://cloud.githubusercontent.com/assets/1610614/19831741/2cebc966-9dd7-11e6-9c8a-4b59579d6e9b.png)
> - First letter: The lookup list includes only the items with the first letter matching.
> 
> ![image](https://cloud.githubusercontent.com/assets/1610614/19831747/38605226-9dd7-11e6-860f-8296f4f149a8.png)

**Comment by marijnh** [comment]
And what is the issue you're reporting?

**Comment by lixiaoyan** [comment]
@marijnh Sorry for the confusion, I updated the title for more clearly.

**Comment by marijnh** [comment]
I'm not taking feature requests for this library. Clients of the JSON interface can do their own filtering, which would be one way to implement this without changing the core library.
