### ISSUE TITLE
Please add methods:

### ISSUE THREAD

**Issue by yaphtes** [ternjs/tern#860]
1)  [String.prototype.padEnd()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd )
2) [String.prototype.padStart()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)

**Comment by marijnh** [comment]
These aren't even finalized in the standard yet, so no, not yet.
