### ISSUE TITLE
Add support for visual studio code 

### ISSUE THREAD

**Issue by kirtangajjar** [ternjs/tern#863]

**Comment by marijnh** [comment]
Out of scope for this project, but you could build it as a separate project.

**Comment by ksmithut** [comment]
@kirtangajjar We need to generate interest in this. I can't believe there isn't already a plugin (or baked in support). I suppose it's because vscode is more of a supporter of typescript, but this would be an excellent addition to the editor.

**Comment by kirtangajjar** [comment]
@ksmithut True that, but visual studio code already has autocompletion for javascript right? Is tern superior to it in any way? I created this issue as I thought the developers missed vscode while supporting other major browsers. However, when @marijnh posted above comment, I checked out some extensions and found that they were maintained by independent devs. So if we want a new plugin, it would probably be created and maintained by the community.

So I think we could generate some interest in it, but i'm unsure if people would be interested or not as vscode already has javascript support.

**Comment by OleksandrNechai** [comment]
>vscode already has javascript support.

True, but it is very primitive:
```js
var x = {x:5, name:""}
f(x);
function f(m){
    m. // no autocomplete
}
```

```js
function f(o){
	return o. //no autocomplete 
}
f({x:5})
```

**Comment by kirtangajjar** [comment]
@marijnh Why is it out of scope? Is maintaining plug in for vs code an issue?

**Comment by marijnh** [comment]
This repository holds the Tern implementation. Plugins can be written an maintained as separate projects. I am not going to do that for you.

**Comment by jcrben** [comment]
fyi, it seems like the VS Code JavaScript Intellisense implementation is called "Salsa"; doesn't seem to be very encapsulated in the codebase; lots of issues referenced under the label https://github.com/Microsoft/TypeScript/issues?q=is%3Aopen+is%3Aissue+label%3ASalsa

**Comment by boniatillo-com** [comment]
I agree this is not the place to request a vscode plugin, but I want to say that I think ternjs is superior to Salsa (the js engine used in vscode).

Salsa uses the same TypeScript engine and it lacks, for example, ES3 prototype inheritance.

I think a smart solution could be to do a Language Server Protocol implementation of ternjs, so it could be used in many other editors, like vscode.

**Comment by tger** [comment]
VSCode does not support AMD modules (such as RequireJS) or AngularJS (i.e. Angular 1.x), Tern would help here.

**Comment by puremourning** [comment]
I believe there is a language server front end for ycmd which has a tern backend, so you could try that.
