### ISSUE TITLE
Integration with Emacs

### ISSUE THREAD

**Issue by anmoljagetia** [ternjs/tern#868]
Hey,

First of all I would like to thank the ternjs team, for coming out with this excellent tool. You guys have done an amazing job!

I am using Emacs and VSCode to write JS mostly. The problem I am facing is, I get perfect completion in VSCode, for example : 

``` javascript
const electron = require('electron')

electron. /* <- Perfect autocompletions */
```

However, using the same in Emacs gives me very generic autocompletions which are not from the electron API, just some standard JS things I am using in the current buffer. Can anyone who has got this working with Emacs, help me set this up?

**Comment by marijnh** [comment]
VSCode actually _runs_ the code in your project, and gets completion info from the result. Tern only abstractly interprets it, which for some kind of code is less accurate. I haven't looked at the way the electron library works, but it might be that it uses constructs that Tern isn't able to handle to create its exports.

**Comment by chemzqm** [comment]
Some of electron API come  from native externsion, so tern doesn't understand.

**Comment by anmoljagetia** [comment]
@marijnh Thanks for the heads up. I can see that this does work with other libraries, like *fs*. I can get those documentation correctly, but unfortunately, can't get the same with electron (and a bunch of others as well).

Is there any way I can get the VSCode like completion within Emacs (or as a matter of fact, vim) ?
P.S. -I also read your book, Eloquent JavaScript, and it's awesome!

**Comment by marijnh** [comment]
The `node` plugin comes with definitions for node's built-in modules. You'd have to write a type definition file (see the `defs` directory in the distribution) to get the same for the electron module.
