### ISSUE TITLE
emacs: jump to definition in imported module

### ISSUE THREAD

**Issue by andreineculau** [ternjs/tern#869]
My `.tern-project` looks like

```json
{
  "libs": [
    "ecmascript"
  ],
  "loadEagerly": [],
  "async": false,
  "plugins": {
    "es_modules": {},
    "node": {}
  }
}
```

Given a project module like

```js
import {
  foo
} from './bar';

foo(1);
```

with the cursor on the last line, I call `tern-find-definition` with `M-.` and the cursor jumps to the 2nd line (`__foo`), but it seems impossible to jump into `./bar.js` to the definition of foo (I tried `M-.` with the cursor on the 2nd line, and nothing).

Am I doing something wrong? Or is it simply not supported/possible?
Thanks!

PS: using latest published (stable) versions of all - tern, tern-mode, node

**Comment by marijnh** [comment]
This worked at one point, but I've also noticed it stopped working. I'll look into it.

**Comment by marijnh** [comment]
Are you using emacs? If so, patch f9bde5792b7 might help

**Comment by andreineculau** [comment]
CONFIRMED! :tada:

`M-.` on the 2nd line goes to the definition in `./bar`
