### ISSUE TITLE
Can't jump to definition for functions exported with shorthand object properties.

### ISSUE THREAD

**Issue by chuym** [ternjs/tern#871]
Using Tern version 0.20.0 on Emacs 25.1. Node version: 6.9.1

Jumping to definition with `tern-find-definition` when cursor in on a shorthand property doesn't work. Using the regular syntax works. Example:

```js
function create() {
  // Implementation
}

module.exports = {
  create
};
```

The above doesn't work.

```js
function create() {
  // Implementation
}

module.exports = {
  create: create
};
```

The above _works_ correctly when the cursor is positioned on the value word (not the property name).

**Comment by TomLingham** [comment]
Yep. Same issue here :(

**Comment by bobrowadam** [comment]
@chuym Did you happen to find a solution for this issue?
