### ISSUE TITLE
emacs: cannot jump to `exports.foo` definition

### ISSUE THREAD

**Issue by andreineculau** [ternjs/tern#873]
given `foo.js` is

```js
export let foo = function() {};
exports.foo();
```

when I am on line 2, and want to jump to the definition of `foo`, all I get is `No definition found`.

my `.tern-project` looks like this

```
{
  "libs": [
    "ecmascript"
  ],
  "loadEagerly": [],
  "async": false,
  "plugins": {
    "es_modules": {},
    "node": {}
  }
}
```

I have the latest published tern emacs package (20161222.850), tern@0.20.0, node@7.3.0.

**Comment by marijnh** [comment]
`exports` is a CommonJS concept, whereas the `export` keyword is something that ES modules use. The two are different module systems, and exporting something like that simply does not add it to `exports`. So this isn't something that can be expected to work.

**Comment by andreineculau** [comment]
true that, I'm using babel's es2015-node4 preset / babel-plugin-transform-es2015-modules-commonjs plugin that makes that possible

**Comment by marijnh** [comment]
I see, I guess it does kind of work in very specific circumstances, but it's not something that either of these module systems define, so it'd be more portable to just refer to the function as `foo` instead of `exports.foo`.

**Comment by andreineculau** [comment]
true that. but we use the `exports.<fun>` pattern because it makes it possible to override them - either in a test environment, or even at runtime (for debugging)
