### ISSUE TITLE
Support JSON type definitions of absolute file path?

### ISSUE THREAD

**Issue by chemzqm** [ternjs/tern#874]
According to the document:
```
The strings given here will be suffixed with .json, and searched for first in the project’s own dir, and then in the defs/ directory of the Tern distribution
```
The type definitions file could only exist in project directory `defs` directory of Tern, I would like to have some of my module share some definitions without copy the definitions file to everywhere.

**Comment by marijnh** [comment]
Could you put them in a separate module, and refer to them as `node_modules/modulename/filename`?

**Comment by chemzqm** [comment]
Normally it should not a problem, but there's some kind of wired project called WeChat mini-APP introduced by wechat and it don't have node_modules support, the developer would not have that folder.

**Comment by marijnh** [comment]
So where _would_ you want to put the definition files?

**Comment by chemzqm** [comment]
A relative file path to the .tern-project file would be easier to share the config file, but an absolute file path support would be good enough.

**Comment by marijnh** [comment]
Relative paths to the .tern-project is how it currently works, isn't it?

**Comment by chemzqm** [comment]
It works, but the document did mention that.
