### ISSUE TITLE
How to auto-generate a JSON type definition file?

### ISSUE THREAD

**Issue by jasonmendes** [ternjs/tern#881]
How were the definition examples in `/defs` made? It seems quite tedious to make by hand! [I started to work on a hacky way](https://github.com/jasonmendes/lodash-tern-definitions/blob/master/index.js) to parse the very detailed comments from `lodash.js` (though there is an `underscore.json` type definition, Lodash various slightly) but I am curious if there is an easier way.

**Comment by marijnh** [comment]
The ones in the distribution were made by hand (and partially by parsing docs) but the `bin/condense` tool can help derive such files from source code.
