### ISSUE TITLE
can't get any functionality out of loadEagerly 

### ISSUE THREAD

**Issue by Dan8720** [ternjs/tern#888]
Hi,

I'm trying to use Tern up an running so it gives me code completions from code in my node_modules folder.

code completions are only working for .js files that share the same parent folder any more complicated folder structures don't work.

I've tried many configurations of .tern-project files and have yet to get anything to work unless it's in the same folder.

I have been trying to use loadEagerly to make sure I have everything I need but it doesn't seem to be doing anything for me how ever I test it.

I have tried different projects.... different .tern-project files I have found online. I can't find any way to make work.

Are there any know issues  or am i just doing this wrong?

Thanks,
Dan

**Comment by marijnh** [comment]
Are you using a module system? If so, you probably don't need loadEagerly.

If not, could you provide a concrete example of what you're doing, and what you expected to happen?

**Comment by Dan8720** [comment]
Hi Marjin,

Thanks for the quick response!

It was my understanding that if I have the project folder in same folder as all my .js files then everything should work it's self out? Is this correct?

I have  a main project folder which has 5 folders of various files types: config files, graphics, scripts, sounds etc.

Tern is working as far as giving me auto completes in the same file. sometimes it will identify a function from a different in a file in the same folder but never any deeper than that.

What I would like to do is to pick up auto- completes from folders in my npm modules .  I have PIXI.js as a dependency and lots of in-house helper functions etc.

I would love to be able to have the argument to those function appear in sublime

I've read the section on config in the manual and it doesn't seem like this should be complicated to achieve but I'm only getting very shallow autoComplete at the moment.

 I have tried listing particularly important files like this

{
  "libs": [
    "jquery"
  ],
  "loadEagerly": [
		"/node_modules/reflex_libs/src/BPlib/BPautoplayManager.js",
		"/node_modules/reflex_libs/src/BPlib/BPtimer.js",
		"/node_modules/reflex_libs/src/BPlib/BPconsole.js",
		"/node_modules/reflex_libs/src/BPlib/BPhelpers.js",
		"/node_modules/reflex_libs/src/BPlib/BPlayoutController.js",
		"/node_modules/reflex_libs/src/BPlib/BPloader.js",
		"/node_modules/reflex_libs/src/BPlib/BPmeter.js",
		"/node_modules/reflex_libs/src/BPlib/BPokBox.js",
		"/node_modules/reflex_libs/src/BPlib/BPreel.js",
		"/node_modules/reflex_libs/src/BPlib/BPreelAnimation.js",
		"/node_modules/reflex_libs/src/BPlib/BPreelBoxStrip.js",
		"/node_modules/reflex_libs/src/BPlib/BPreelManager.js",
		"/node_modules/reflex_libs/src/BPlib/BPresourceManager.js",
		"/node_modules/reflex_libs/src/BPlib/BPskinnedBox.js",
		"/node_modules/reflex_libs/src/BPlib/BPsoundManager.js",
		"/node_modules/reflex_libs/src/BPlib/BPstakeSelectionPopup.js",
		"/node_modules/reflex_libs/src/BPlib/BPstandardObjectFactory.js",
		"/node_modules/reflex_libs/src/BPlib/BPstreamedVideoPanel.js",
		"/node_modules/reflex_libs/src/BPlib/BPsystem.js",
		"/node_modules/reflex_libs/src/BPlib/BPsystemOverlay.js",
		"/node_modules/reflex_libs/src/BPlib/BPtextureParser.js",
		"/node_modules/reflex_libs/src/BPlib/BPtouchAreaManager.js"
  ],
  "plugins": {
    }
  }
}

I have also tried "/node_modules/reflex_libs/src/BPlib/*

I have tried this too.

{
    "plugins": {
        "es_modules": {}
    },
    "libs": [
        "ecma5",
        "ecma6"
    ],
    "ecmaVersion": 6
}

Am I just missing something on how I'm suppose to configure the project?
Any guidance would be much appreciated.

Thanks,
Dan

**Comment by marijnh** [comment]
So are you using a module system? Are you using `require` to pull in your dependencies?

**Comment by Dan8720** [comment]
No I'm not using require it's a module system. I use npm to pull everything in.

**Comment by marijnh** [comment]
So you want to load stuff into the global namespace? That is indeed what loadEagerly can be used for. Have you tried removing the leading slash in the filenames, so that they won't be interpreted as absolute paths? Also, you can use wilcards, so `loadEagerly": ["node_modules/reflex_libs/src/BPlib/*.js"]` should do.

**Comment by Dan8720** [comment]
{
	"libs": [
		"jquery"
	],
	"loadEagerly": [
		"node_modules/reflex_libs/src/BPlib/*.js",
	  	"node_modules/pixi.js/dist/pixi.js
	],
	"plugins": {}
}

I've got this now and it's all working brilliantly. I think it must have been that I was using absolute paths.

Thanks a lot for your help!!
Dan
