### ISSUE TITLE
[Suggestion] I think the name of `.tern-project` file is a little bit confusing.

### ISSUE THREAD

**Issue by BurningLutz** [ternjs/tern#889]
Hi guys. First thank you for the hard work to this project, it's AMAZING! And I have some words to say about the configuration file `.tern-project'.

I tried to make it work in vim (via the `tern_for_vim` plugin), and almost everything works well except that the tern seems not recognizing my tern configuration file placed in the root of my project dir.

I spent hours trying to figure it out but got nowhere.......until I realized that the `.tern-project` is the full-name of the configuration file rather than an ext-name. 

When the first time I saw the `.tern-project`, I can't help treating it as an ext-name because I've seen lots of project related files were named as `foo.bar-project`, so I'm wondering why not name the tern configuration file as `.ternrc` or something?

**Comment by marijnh** [comment]
Because that'd be an incompatible change and the motivation for it seems to be pretty thin.
