### ISSUE TITLE
Using tern in code mirror editor getting type error

### ISSUE THREAD

**Issue by dianavazquez** [ternjs/tern#892]
Has anyone encountered this error before?

Uncaught TypeError: Cannot assign to read only property 'parentNode' of object '[object HTMLInputElement]'
    at infer.js:1992
    at infer.js:21
    at infer.js:22

**Comment by marijnh** [comment]
You probably have an element on your page with id `exports`. That confuses the universal module loader into thinking it's in a CommonJS module environment. The easiest solution would be to change the id of the module. An alternative is to create your own global `var exports = null` variable to shadow the id.
