### ISSUE TITLE
Auto generate

### ISSUE THREAD

**Issue by fxfactorial** [ternjs/tern#895]
Is there an accepted autogenerator for `.tern-project` files from package.json, or maybe a yarn lock file?

**Comment by marijnh** [comment]
I'm not aware of such a tool

**Comment by fxfactorial** [comment]
@marijnh thanks, would you be alright with the command line tern providing that functionality ?

**Comment by marijnh** [comment]
What kind of information would you get from package.json that'd help configure .tern-project?

**Comment by fxfactorial** [comment]
@marijnh Well tern doesn't work as well unless I explicitly give some paths to `loadEagerly`, 

```
 "loadEagerly":[
    "node_modules/react/dist/react.js",
```
and so on. 

I can just generate that from package.json instead of having to hand write it each time.

**Comment by marijnh** [comment]
If you use a module system, that shouldn't be necessary -- in fact, I'm not sure how it could help at all, unless you're getting bindings from the global scope.

**Comment by fxfactorial** [comment]
This is consistently true on the node side, I get better code completion and type info when I explicitly give the path to the index.js of a project.

**Comment by marijnh** [comment]
Can you provide a minimal example of a project where this is true, and define 'better code completion' more precisely?

**Comment by fxfactorial** [comment]
Yes sorry, I will whip something up.

**Comment by repus** [comment]
Open that tool

**Comment by fxfactorial** [comment]
@marijnh 

ReactNative example. 

1. reactnative  init someproject
2. yarn
3. do: import { App<HERE DO tern-complete > } from 'react-native';

Without a .tern-project file containing the loadEagerly to react-native's node_module, I get no code completion. When I add the respective path, then I get code completion of App{State, Registry}

**Comment by marijnh** [comment]
The `react-native` module does not appear to export a binding `App`, going by [this file](https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native-implementation.js), which is the main module of the library.

**Comment by fxfactorial** [comment]
This was just one example, it still the case that giving a full path help code completion

**Comment by marijnh** [comment]
I've never used react native, and if you can't give me an actually correct example I won't be able to look at this.

**Comment by fxfactorial** [comment]
It had nothing to do with react native besides being an example. 

I can give other examples as well.

**Comment by fxfactorial** [comment]
@marijnh Ping. 

Here is an example repo that shows what I'm talking about. 

https://github.com/fxfactorial/animations

Only two commits, first one without .tern-project file and one with it. In the first commit, I get this auto completion
(207309504912481b4e4e1728d072dfb71a63f795)
<img width="315" alt="screen shot 2017-08-08 at 1 42 37 am" src="https://user-images.githubusercontent.com/3036816/29063696-82d63da6-7bdb-11e7-8d20-efac8e164b4a.png">

But in the second commit, where I help out tern with the tern-project file paths hard coded, then I get much better code completion 

(2c612e77168a41e87a2583003881337c074fdb28)
<img width="463" alt="screen shot 2017-08-08 at 1 46 10 am" src="https://user-images.githubusercontent.com/3036816/29063732-9a6549c6-7bdb-11e7-89f3-ea754a5d672e.png">

**Comment by fxfactorial** [comment]
@marijnh Ping: I realize you're busy, just letting you know I made the example project as you requested.
