### ISSUE TITLE
Handling symlinks in VMs/containers

### ISSUE THREAD

**Issue by AGhost-7** [ternjs/tern#900]
On my projects I use virtual machines or containers to run my applications from. The issue I'm currently running into is that tern cannot resolve symbolic links (which are used by e.g., `npm link`) that are created from the container/VM. I often work on multiple modules at the same time and this is essential for my work.

Lets say for example you have an application located in `/home/aghost/workspace/app/index.js`:

```
var app = require('express')()
var Model = require('orm').Model
// etc...
```

The `orm` module is linked from the vagrant VM environment (as the application _needs_ to run from the VM environment). The symbolic link is actually for the path `/home/vagrant/workspace/orm`, which is invalid from the host. The location of the `orm` module on the host would be `/home/aghost/workspace/orm`.

My solution would be to add a configuration option to "remap" the dependencies to a different location, essentially forgoing symbolic link resolution. I'd be more than willing to open a PR to fix this.

**Comment by marijnh** [comment]
You might have some luck abusing the `normalizeFilename` option to the server constructor for this, though that's not currently something that plugins can extend. A possible strategy would be to allow plugins to do that and write this as a plugin.

**Comment by AGhost-7** [comment]
The issue I'm seeing here is that `resolveToFile` returns null. I don't think I can rely on `normalzeFilename`.

**Comment by marijnh** [comment]
Ah, that's a good point. Yeah, then that won't work. I'm not really interested in including this obscure use case as a feature in the base library, but if you write a plugin and need some new type of customization to be able to implement it, you can propose it with a pull request.

**Comment by AGhost-7** [comment]
This is afaik a few lines of code (~5 lines) to implement in node_resolve afaik. Is it really worth implementing as a separate module?

**Comment by marijnh** [comment]
Oh, that is indeed much simpler than I expected. Merged as 54b5bf3

**Comment by marijnh** [comment]
And reverted again since it doesn't seem to actually be a patch that works.

**Comment by AGhost-7** [comment]
That's why I was going to test :S
