### ISSUE TITLE
With global-hl-line-mode enabled, tern-find-definition doesn't highlight the line it jumps to

### ISSUE THREAD

**Issue by zeusdeux** [ternjs/tern#901]
Hey, I am unsure if this a `tern` issue or a `hl-line` issue. Posting here to sort this out collaboratively as I am not very good with emacs internals and debugging in it (especially post command hooks) in general.

#### Observed behaviour:

When I run `tern-find-definition` (bound to `M-.`) on a symbol, the cursor correctly jumps to the location where the symbol was declared. But, the line the cursor _jumped to_ is not highlighted. Instead the line the cursor _jumped from_ remains highlighted.

#### Steps to reproduce

1. Create a js file with the following contents:

  ```js
  const a = 42
  module.exports = a
  ```
2. Move the cursor on the usage of symbol `a`
3. Invoke `tern-find-definition`

#### Metadata

Tern - v0.21.0
Emacs - Commit 0943cc1 (`brew` installed using `--HEAD`)

![tern-hl-line-bug](https://cloud.githubusercontent.com/assets/635512/25565486/fa9186dc-2dc7-11e7-9b24-36ffa9f58102.gif)

Thanks in advance folks!

**Comment by marijnh** [comment]
I'd say that is an issue with `hl-line`, but I'm also not super knowledgeable about all the obscurities of elisp programming. Still, going to close this since I'm not planning to debug it myself. If you ever find a solution that requires a change to tern.el, feel free to open a PR.
