### ISSUE TITLE
Ternjs doesn't infer all types avaible

### ISSUE THREAD

**Issue by iglosiggio** [ternjs/tern#904]
I was coding a fairly simple function that performs bash-like brace expansion:
```js
function brace_expand(str) {
  const matches = str.match(/{[^{}]*}/g) || [];
  const obj_matches = matches.map(function create_obj_match(matchText) {
    return { match: matchText, replacements: matchText.slice(1, -1).split(/,/) };
  });
  const strings = obj_matches.reduce(function use_obj_match(strings, match) {
    return strings.reduce(function replace_matches(strings, string) {
      return strings.concat(match.replacements.map(function replace_match(replacement) {
        return string.replace(match.match, replacement);
      }));
    }, []);
  }, [str]);
  
  return strings;
}
```

I was surprised that ternjs typed it as `fn(str: ?) -> [?]` instead if `fn(str: string) -> [string]` or even `fn(str: ?) -> [string]`, but then i saw it:
```js
const matches = str.match(/{[^{}]*}/g) || [];
```
`matches` was typed as `[?]` instead of the correct `[string]`, because of the `[]` failsafe for when string.match returns null (the same happens on `obj_matches.reduce` because of the `[]` initial value).

Using `[''].slice(1)` typed correctly ¿Is there any way to make improvements on typing this kinds of functions? ¿Does ternjs have some type of hinting mechanism?

PD: Thanks for this project! I love to have good type inference on vanilla JS w/o the necesity of transpiling from another JS-flavor

**Comment by marijnh** [comment]
> matches was typed as [?] instead of the correct [string], because of the [] 

Not quite -- it's not aware of the type of `str`, and thus doesn't produce a type for `str.match()`. If you call your function with a string, the type is adjusted to `[string]`.

> Does ternjs have some type of hinting mechanism?

You can enable the doc_comment plugin (it's on by default), and write jsdoc-style comments.

**Comment by iglosiggio** [comment]
Oh, thanks but why `str.match(...)` was  typed as `[string]`?

**Comment by marijnh** [comment]
If you directly ask for the value of an expression, the result will include guessed types (in this cause, it used the method name to guess that this is probably `RegExp.match`). But those aren't fed into the type graph, since they'd pollute it with all kinds of nonsense, so they don't end up influencing other types that depend on that one.

**Comment by iglosiggio** [comment]
Si if i do something like `const true_str = str +'' ;` it would type like
wanted originally​?

**Comment by marijnh** [comment]
> Si if i do something like `const true_str = str +'' ;` it would type like wanted originally​?

It would, because adding something to a string will always produce a string. But that's a completely different example than the one above.

**Comment by iglosiggio** [comment]
Thanks for the response!

I tested forcing str to be a string but then this didn't gave the types that i expected

```js
const strings = obj_matches.reduce(function use_obj_match(strings, match) {
  return strings.reduce(function replace_matches(strings, string) {
    return strings.concat(match.replacements.map(function replace_match(replacement) {
      return string.replace(match.match, replacement);
    }));
  }, []);
}, [str]);
```

...unless i forced  the initial value of `reduce_matches` to type as `[string]` by doing something like `[''].slice(1)`

¿Is this expected behaviour?

PD: Thanks for all the responses, ternjs is a really interesting project for me and is helping me a lot in understanding how type inference is done in general

**Comment by marijnh** [comment]
I don't understand what you mean, and I don't see `reduce_matches` in the example code. Can you provide a smaller/clearer example?

**Comment by iglosiggio** [comment]
Sorry, it was a typo, i meant replace_matches

**Comment by marijnh** [comment]
The expression doesn't seem to include any concrete types, and uses methods to produce new values, which also can't be definitely resolved if Tern doesn't know the type of the object, so it isn't surprising that it's not producing a concrete result type.

**Comment by iglosiggio** [comment]
Thanks!
