### ISSUE TITLE
Support for class fields

### ISSUE THREAD

**Issue by renatofdds** [ternjs/tern#909]
Although Tern can parse the identifier on point after some property initializer on some class, it fails to find the definition.

```JS
let Test = { b: 1 };

class Example {
    a() {
        Test.a = 1;
    }

    fieldX = ''

    b() {
        Test.b = 1;
    }
}
```
Find definition on ```Test``` on method ```a()``` works but not on method ```b()```, failing with "No type found at the given position.".

Reference for the proposal: [ES Class Fields & Static Properties](https://github.com/tc39/proposal-class-public-fields)

**Comment by marijnh** [comment]
Class fields are not part of the language yet, and Tern doesn't support any unfinished language features. Closing this until this is stabilized.

**Comment by qstrahl** [comment]
@marijnh [This has been combined with another proposal and is now at stage 3](/tc39/proposal-class-fields). Is that sufficient to warrant development for tern support, or does it have to be at stage 4 first?

**Comment by marijnh** [comment]
There is not really a stage at which something automatically gets implemented in Tern. This project is in low-maintenance mode, so support for new features doesn't just materialize. Most likely, it'd have to be contributed by the community.

**Comment by qstrahl** [comment]
Totally understandable - what I meant to ask was, if a PR with no issues were to materialize tomorrow for this feature, would it get merged? :D

**Comment by marijnh** [comment]
Yes, probably.
