### ISSUE TITLE
Need initial guidance on how to support an object framework

### ISSUE THREAD

**Issue by DamienCassou** [ternjs/tern#911]
I would like to adapt tern so that it understands our class-based object model [klassified](https://github.com/foretagsplatsen/klassified) (also see introductory blog-posts [1](http://nicolas.petton.fr/blog/simple-object-model-javascript.html) and [2](http://nicolas.petton.fr/blog/simple-object-model-javascript-2.html) if you want to know more). For example, in a `foo.js` file:

```js
define(['klassified'], function(klassified) {
  let foo = klassified.object.subclass((that, my) => {
    that.foobar = function(a, b) {
      return a + b;
    };
  });

  let myobj = foo();

  myobj.foobar(3,4);
  myobj.foobar(5,3); // completion won't tell me the parameters types

  return foo;
});
```

A small problem is that tern never learns that `myobj.foobar()` takes 2 integers. The most important problem to me is when I want to instantiate `object` from elsewhere (e.g., `bar.js`):

```js
define(['./foo'], function(foo) {
  let myobj = foo();
  myobj.foobar(3,4); // completion won't tell me foobar() is in the API of myobj!
});
```

Can you please point me where I should start to implement such support? Are there similar plugins around to get inspiration from?

Thanks

**Comment by marijnh** [comment]
If you can express the things your helper functions do with 'effects' (search through `ecmascript.json` for `!effects`, for examples — these do things like copying properties from one argument to another), you might be able to just write a .json file and load it as a library definition. If it does more complicated things, you'll have to write a plugin that defines custom handlers for some functions -- see for example `Object.create` in the standard definitions, which calls `Object_create` defined in `lib/def.js`.
