### ISSUE TITLE
calling addDefs in postParse does not work

### ISSUE THREAD

**Issue by mohitleo9** [ternjs/tern#916]
Hi, 
I am trying to create a new plugin for a class definition library (it lets you create classes with lots of meta info (like types of props among other things) that I use for some of my personal projects. Since the it's a class definition library I want to add the definitions after I have the ast (in postparse) But if I try to addDefs in postParse the completions don't work.

I want to do something like 
```javascript
tern.registerPlugin("jug", function(server, options) {
	 var defs = {
    "!name": "jug",
    "!define": {
      "Talk": {
	"!type": "fn(author: string, topic: string)",
	"prototype": {
	  "author": "string",
	  "topic": "string"
	}
      },
      },
    "JUG": {
      "Factory": {
	"create" :{
	  "!type" : "fn(id: string) -> !custom:jug_create"
	}
      }
    }
  }
	  server.on('postParse', function(ast, text) {
              this.addDefs(defs)
	  });
	 

    //return {
    // defs : defs
    //};
  });
```

If I return {defs} from registerPlugin function everything works but not if I call this.addDefs.

**Comment by mohitleo9** [comment]
Not sure if this is helpful the class library structure looks like

```javascript JS.create('ClassName', {
	methods: {
		print: function(){
		 console.log(this.name);
		}
	}
	fields: {
		name: {
			type: 'String',
			init: 'Joe'
		}
	}
	constructor: function(name){
	    this.name = name;
	}
})
```

**Comment by marijnh** [comment]
Definitions work in a way that requires them to be loaded before code analysis starts. When possible, you can just load all the definitions you may need under some namespace, and connect them as appropriate during analysis (like the node addon does for builtin modules). If that's not possible, I don't have a solution.

**Comment by mohitleo9** [comment]
Thanks a lot! that worked!
