### ISSUE TITLE
modules plugin options clarification

### ISSUE THREAD

**Issue by bfulop** [ternjs/tern#926]
I'm trying to exclude/include modules to be scanned by ternjs and I see some confusion about the syntax.

In [several](https://github.com/ternjs/tern/issues/902#issuecomment-304427640) [places](https://atom.io/packages/atom-ternjs), I see the recommendation to set a file path glob pattern for the `dontLoad` property:

```json
"dontLoad": [
    "node_modules/**",
    "path/to/your/js/**/*.js"
  ],
```

The [docs](http://ternjs.net/doc/manual.html#plugin_modules) and the [source](https://github.com/ternjs/tern/blob/3f8a2bc7c2e9a4ac55e8c6f6c60c0634cbe71326/plugin/modules.js#L49) however state that the `dontLoad` or `load` properties are

1.  converted to regex
2. test the `name` of the module (not the path). 

So in my experience the correct syntax to include files is this:

```json
  "plugins": {
    "node": {},
    "modules": {
      "load": "^(.{1,2}/)+|testdouble|mongodb"
    }
  }
```

This includes all files that are imported from my local code (e.g.: `require('./foo')`, plus the `testdouble` and `mongoldb` npm modules.

**Comment by othree** [comment]
There are two place accepts `dontload`
One is inside plugin modules, which use regexp.
Another place is root level, use [minmatch](https://www.npmjs.com/package/minimatch) which support glob.

code for second place: https://github.com/ternjs/tern/blob/870997591e463fea3dd478ac903c697e96e30189/bin/tern#L170
