### ISSUE TITLE
How can I use ramda's type signatures in a type definition file?

### ISSUE THREAD

**Issue by haakenlid** [ternjs/tern#931]
I'm trying to create a type definition for ramda.js  https://github.com/ramda/ramda/issues/2270
Since all relevant data can be found in the dist file [/dist/ramda.js](https://raw.githubusercontent.com/ramda/ramda/master/dist/ramda.js) I've just used some regular expressions to pull out the docstring and type signature and created a `ramda.json` where each entry has this structure:

```
 "replace": {
      "!url": "http://ramdajs.com/docs/#replace",
      "!type": "RegExp|String -> String -> String -> String",
      "!doc": "Replace a substring or regex match in a string with a replacement."
    },

```
The `!type` field is taken from the JSdoc `@sig` field and is a [haskell-style notation](https://github.com/ramda/ramda/wiki/Type-Signatures). All the ramda library functions are curried. So calling `R.replace('foo', 'bar', 'foobar')` gives the same result as `R.replace('foo')('bar')('foobar')` 

Ternjs uses a different type signature scheme. If I try to use my type definition file, tern will crash with various `Unrecognized type spec` or `Invalid !type spec` errors.

Removing the `!type` fields makes tern work, but I then I don't have the type signatures. I guess I could add the signature at the start of the doc field, but it's not an optimal solution.

I've looked at Tern's documentation and the sample definitition files, but it's not clear how to translate the ramda types signatures into something that tern can parse. And I could not figure out how to represent union types such as `RegExp|String` with tern's type scheme.

I would like to make the translation as automated as possible, since there are about 250 functions, and I'm not confident that I could do an accurate translation manually.

**Comment by marijnh** [comment]
Union types are supported, also using the `|` operator. But curried functions aren't something that Tern supports, and neither is trying to write types using a completely different syntax, clearly. So I think your best bet is to simplify these down to uncurried form, and adjust the syntax to use Tern's conventions.

**Comment by haakenlid** [comment]
How do I use the `|` operator? I couldn't find anything about it in the documentation. 

If I try this: `"!type": "fn(regexp|string, string, string) -> string"` it shows up as `fn(string, string, string) -> string`

**Comment by marijnh** [comment]
`regexp` isn't a type that Tern knows -- it uses `RegExp` for regular expressions. Maybe that's the issue.

**Comment by haakenlid** [comment]
I found an example in one of the definition files. It seems to work with `+RegExp|string`. Is there some documentation about which types are built in, and how to define your own types? 

Ramda uses a lot of placeholder types. For instance, `compose` has this type: `((y → z), (x → y), …, (o → p), ((a, b, …, n) → o)) → ((a, b, …, n) → z)`. 

`fn([fn()]) -> fn()` is the best I could come up with, but it's not that accurate.

**Comment by marijnh** [comment]
> Is there some documentation about which types are built in, and how to define your own types?

Apart from the built-in types like number and string, types correspond to constructors.

Generic types are not supported. Trying to declare a global `a` type wouldn't work — every use of a will be unified, leading to a huge messy union type.
