### ISSUE TITLE
module.exports don't show up in condense output.

### ISSUE THREAD

**Issue by mohitleo9** [ternjs/tern#932]
Hey, 
Trying to create a ctags plugin (actually extend one) which uses tern/bin/condense to get the type info, I noticed that it does not show info from `module.exports` so just want to find out if that's intentional and if there's any way to get around it?

**Comment by mohitleo9** [comment]
Probably related to issues like https://github.com/ternjs/tern/issues/871.

**Comment by marijnh** [comment]
> I noticed that it does not show info from module.exports

It does and it has tests for that, so a concrete example would be useful.

**Comment by mohitleo9** [comment]
Tern is working properly, the problem was in some other plugin. thanks!
