### ISSUE TITLE
Tern autocomplete does stopped working

### ISSUE THREAD

**Issue by CSRaghunandan** [ternjs/tern#936]
Ternjs is not working for me anymore. I'm getting this error: `Request failed: ((wrong-type-argument url nil))`

I've build emacs from source recently and running on macOS Sierra with the latest version of tern for `npm` package manager as well.

Any idea how to fix this?

**Comment by marijnh** [comment]
I've never seen this, it's possible some library that tern.el depends on changed in an incompatible way--you'll have to debug it to find out.

**Comment by CSRaghunandan** [comment]
could it be something in emacs master that is causing ternjs to fail?
