### ISSUE TITLE
Jump to definition to jsx module.

### ISSUE THREAD

**Issue by itome** [ternjs/tern#939]
I use tern in Emacs(Spacemacs) and I feel happy with tern mode. But one issue is that It can't reach to jsx module by jump to definition.
```
import SomeModule from './somemodules.js'; 
              ^ <- jump to definition here, and it can reach to the file.
import SomeView from './someview.jsx';
              ^ <- jump to definition here, and it can't reach.
```
Any idea can be helpful.

tern-mode version: tern-20170925.1333

**Comment by sandinmyjoints** [comment]
Seems like this is probably a dupe of https://github.com/ternjs/tern/issues/579.

**Comment by itome** [comment]
@sandinmyjoints 
thank you. I close this issue and continue discussing at #579
