### ISSUE TITLE
Autocomplete of method parameters

### ISSUE THREAD

**Issue by sebasmoyano** [ternjs/tern#942]
It would be great to support autocomplete of method parameters. For example if a method receive a string parameter be able to list the possible values for that string.

**Comment by angelozerr** [comment]
Please try https://github.com/angelozerr/tern-guess-types

**Comment by sebasmoyano** [comment]
Great! Thanks for the quick response.

**Comment by sebasmoyano** [comment]
mmm sounds like it doesn't fit my requirements. Any chance to list literal values during autocomplete. E.g.:
`
record.field('path'); // when autocomplete path it should display a list of fixed strings.
`
