### ISSUE TITLE
Example of .tern-project for React Native Apps?

### ISSUE THREAD

**Issue by paymog** [ternjs/tern#946]
I just discovered tern and I'm having trouble setting it up to work with my react native app. I followed the docs for [tern vim](https://github.com/ternjs/tern_for_vim) by installing with Pathogen and running `npm install` in `~/.vim/bundle/tern_for_vim`. I've installed [maralla's completer](https://github.com/maralla/completor.vim) and set `let g:completor_node_binary = '/usr/local/bin/node'` because I installed node through Homebrew. I've created a react native project and put the following `.tern-project` file in the root:

```
{
  "libs":[
    "browser",
    "chai",
    "ecma5",
    "ecma6",
    "jquery",
    "underscore"
  ],
  "plugins": {
    "angularjs": {},
    "commonjs": {},
    "complete_strings": {},
    "doc_comment": {},
    "es_modules": {},
    "modules": {},
    "node":{},
    "node_resolve":{},
    "requirejs": {},
    "webpack": {}
  }
}
```

which I sourced from [this source](https://gist.github.com/vmlinz/6fc6949cbd0e378e55c951cb2d87b1dd).

However, when I open `App.test.js` and try to write some code, I don't get any completion at all. Ideas on what might be going wrong?

**Comment by lecler-i** [comment]
Are you sure `tern` process is running ?
If not, run it in the project folder (it will create a `.tern-port` file that vim extension will use to give you the autocompletion.

No specific config is required for ReactNative, as it is a NodeJS project like any other.

**Comment by othree** [comment]
The sample `.tern-project` file is not compatible with latest release.
You should make sure tern is running first.
