### ISSUE TITLE
load resolved modules

### ISSUE THREAD

**Issue by TitanNano** [ternjs/tern#952]
in tern/plugin/modules.js resolved modules are added to the know files but the file content is not loaded. This means none of the types and objects in the loaded module are known to tern unless I explicitly add this module file by opening it in my editor.

Can we just load the resolved module in tern? This could be put behind an option.

**Comment by marijnh** [comment]
> but the file content is not loaded. 

What do you mean by that? The tests, for example, verify that types from modules make it into the analysis.

**Comment by TitanNano** [comment]
yes I now know what was causing this behavior. 
atom-tern by default configures the modules plugin like this:
```JSON
"modules": {
    "dontLoad": "",
    "load": "",
    "modules": ""
}
````

Which causes all modules to not be loaded.
