### ISSUE TITLE
Expose `findExprType` on tern's API

### ISSUE THREAD

**Issue by ronami** [ternjs/tern#959]
Hey,

I'm writing a tern plugin and I need to get the type of an expression. I can easily do that with `findExprType` (https://github.com/ternjs/tern/blob/master/lib/tern.js#L875) but it's not exposed (can be exposed like other methods such as https://github.com/ternjs/tern/blob/master/lib/tern.js#L843).

I will be happy to make a PR for that, please let me know if it makes sense and I will.

I know this project is no longer being actively maintained but this is a really small change and it would save me from having to maintain and publish my own fork. Merging a PR like that should be a matter of minutes.

Thanks! :)

**Comment by marijnh** [comment]
Does `infer.expressionType` cover your needs? `findExprType` seems to be written for server requests (taking a query object as parameter), and might not be much use as a utility function.

**Comment by ronami** [comment]
It does, `infer.expressionType` is exactly what I needed, thank you for the quick response :)
