### ISSUE TITLE
Tern not autocompleting node modules

### ISSUE THREAD

**Issue by joshmin98** [ternjs/tern#962]
I've installed tern and am using it in emacs (I've installed and configured the tern package and company-tern), and I've created a .tern-project file:

` 
{
"plugins": {
    "node": {}
    }
}
`

However, when I'm editing I tern does not recognize any of the packages I've installed through npm. Am I doing anything wrong? I've read through the documentation and similar issues but I haven't found a fix for my issue.

**Comment by othree** [comment]
Maybe you are looking for another plugin called`node_resolve`.
Which help tern resolves npm modules.

**Comment by sof5sof** [comment]
> Maybe you are looking for another plugin called `node_resolve`.
Which help tern resolves npm modules.

The manual states that `node_resolve' is loaded already by the `node` plugin.

From the manual:
>  Node.js plugin
The node.js plugin, called "node", provides variables that are part of the node environment, such as process and __dirname, and loads the `commonjs` and `node_resolve` plugins to allow node-style module loading.
