### ISSUE TITLE
Custom resolvers for requirejs

### ISSUE THREAD

**Issue by vlada79** [ternjs/tern#963]
Similar to `commonjs`, `module` and `node_resolve` plugins, it would be useful to have ability to add custom resolver plugins for requirejs.

**Comment by ctaylo21** [comment]
@vlada79 It does have support for requireJS. See: http://ternjs.net/doc/manual.html#plugin_requirejs

For my project, I have something like this in my `.tern-project` file:

```
  "plugins": {
    "requirejs": {
      "baseURL": "./static/js/",
      "paths": {
        "analytics": "./analytics/_module",
        "analyticsSub": "./analytics",
        "api": "./api/_module",
        // more modules
      }
    }
  }
```
