### ISSUE TITLE
tern.el not working with emacs latest version

### ISSUE THREAD

**Issue by boehm-s** [ternjs/tern#965]
I'm trying to use `tern` with the latest version of emacs (27 : master branch) and I'm getting the following error : 

```
Request failed: ((wrong-type-argument Need a pre-parsed URL. [cl-struct-url http nil nil 127.0.0.1 39585 / nil nil nil nil t] url))
```

It seems to come from `tern-req` function, this line : 
```
(url (url-parse-make-urlobj "http" nil nil tern-server port "/" nil nil nil))
```

But I don't know how to fix it, 'cause I'm not familiar with lisp development

**Comment by c0001** [comment]
Yes the same of me . 

emacs version: 26.1-rc1 and 27.0.50

```
(url (url-parse-make-urlobj "http" nil nil tern-server port "/" nil nil nil))
```

Does the maintainer didn't have the willing or be out of steam of it?

Hope for fixing and Regards 😄

**Comment by iambumblehead** [comment]
tern is no longer maintained https://github.com/ternjs/tern/commit/ae83725819286d3f134a6b9956f1117b341e1040

**Comment by boehm-s** [comment]
Hi again,

I asked for help on emacs stackexchange and found it :) 
There is no problem with tern itself, you just need to re-compile it with your version of Emacs.
[Here is the link to the solution](https://emacs.stackexchange.com/questions/40865/emacs-lisp-error-need-a-pre-parsed-url).
