### ISSUE TITLE
Tern takes a lot of Memory around 1.0 GB

### ISSUE THREAD

**Issue by aswinmohanme** [ternjs/tern#966]
I noticed that after some time the memroy usage of tern process was around 1.0 GB.

Here is my .tern-project file

```
{
  "libs": [ ],
  "loadEagerly":[
  ],
  "plugins": {
    "node": { },
    "requirejs" : { },
    "es_modules" : { },
    "doc_comment": { "fullDocs": true },
    "complete_strings": {}
  }
}
```

This was while working on a React Native Project. I'm using the latest version of all plugins and tern

**Comment by chemzqm** [comment]
acorn has issue with jsx， one way is to use acorn jsx

**Comment by aswinmohanme** [comment]
I don't understand

**Comment by chemzqm** [comment]
@aswinmohanme acorn is the engine of tern, see https://github.com/RReverser/acorn-jsx
