### ISSUE TITLE
Want to help maintain TernJS

### ISSUE THREAD

**Issue by othree** [ternjs/tern#969]
Hi @marijnh 

I want to help maintain TernJS.
I still saw many tools depend on TernJS to provide complete function for JS.
So I hope this project can keep update.

I don't have much experience on this kind of tools.
At least I can update defs to latest standard, fix bugs and update parser to support new syntax.

**Comment by marijnh** [comment]
That'd be wonderful! I see you've submitted some pull requests in the past. I've invited you as a contributor.

Please be careful what you merge—the library has been unmaintained for a while, but as you mention, lots of people are relying on it!

Some of the code is sadly very complicated and confusing, but if you have specific questions on how something works, write me an email, and I'll see if I remember. If at any point you feel there should be another release, also get in touch.

**Comment by othree** [comment]
Thanks, I will update the definitions first.
Then start to see issues and PRs.

**Comment by pappasam** [comment]
@othree any thoughts on updating the readme to indicate that you're maintaining the project? It will prevent the community from switching from ternjs to (imho, worse) alternatives (like typescript server). Thanks for stepping up, I appreciate it and I'm sure many other people do too!

**Comment by othree** [comment]
@pappasam Thanks, I will update it later.
