### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by y-ates** [ternjs/tern#970]
**1. Mistakenly single option for autocomplete** 
Take for example the following code:

```
var tmp = document.createElement("script");
tmp.setAttribute("src", "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js");
document.getElementsByTagName("body")[0].appendChild(tmp);

tmp.     // <--- start autocomplete (M-tab) 
```
Here it will automatically fill "setAttribute". But there are other functions which could be called.

same here: 
```
    var rawFile = new XMLHttpRequest();

    rawFile.overrideMimeType("application/json");
    rawFile.open("GET", file, true);

    rawFile.     // <--- start autocomplete (M-tab) 
```
Here it fills it with "onreadystatechange". I guess there are more cases.

**2. Missing autocomplete** 
Take for example the following code:

```
document.     // <--- start autocomplete (M-tab) 
window.         // <--- start autocomplete (M-tab) 
console.        // <--- start autocomplete (M-tab) 
```
I dont know if these cases are special, so I am not sure if there is more like this. But trying to autocomplete these will fail and nothing will be offered (autocomplete returns "no match").

**Comment by othree** [comment]
Hi I think you need setup `.tern-project` and add `browser` lib.

```json
{
  "libs": [
    "browser"
  ]
}
```

**Comment by y-ates** [comment]
Ah, yes. You were right. Thanks in advance :)!
